Sprite Sheet Modding, Panel Drawing Revamp, and Panel Skin Mixing
panel-attack/panel-attack pull request #1172
Opened 2024-04-20 23:06 UTC by DonavinDraws

* Panel mods and panel rendering are now done using sprite sheets.
* Old mods are automatically converted into compatible sprite sheets.
* Also minor implementation of allowing players to select skins for individual panels.

2024-04-20 23:41 UTC, Endaris reviewed
Just some general comments, going to review the functional part more closely tomorrow.

2024-04-20 23:41 UTC, Endaris commented on .vscode/launch.json
Please add the launch.json to your .gitignore as it will cause conflicts for everyone else.

2024-04-20 23:41 UTC, Endaris commented on consts.lua
> +-- How long newly-transformed panels from fromGarbage will hover before falling, in frames.
This looks like an unintentional Ctrl+H

2024-04-20 23:41 UTC, Endaris commented on main.lua
> +end
lldebugger already gets started upon passing the `debug` argument via `developer.lua` so you should still be able to debug after removing this code.

2024-04-21 16:29 UTC, Endaris requested changes
This might require a bit of patience on both ends.
This is a broad review of the code, I haven't tested it yet because it crashes on startup due to the changes you made for the panel skin mixing. Please remove that part of the code for now as I'm not willing to consider it in the same context as the other changes you made.

2024-04-21 16:29 UTC, Endaris commented on config.lua
> +    panels                     	  = {}, -- setup later in panel init
I assume this is to accomodate your idea of selecting panels of different sets in select_screen.
For this PR I would ask you to revert all changes related to that as it is much more controversial feature than enabling the use of spritesheets for panel sets, in fact to the point that I wouldn't accept it without involving the community in a bit more of a discussion because I believe there are much better options if we aim for improved customization for a variety of reasons.

Additionally using volatile data types for effectively global properties has proven to be a terrible idea for maintainability, in this case exceptionally so because this value is also used in online so it extends to serialization. 
It is also what causes the PR to crash for me at the moment so I can't test it to verify it works how I thinks it does.

2024-04-21 17:11 UTC, DonavinDraws commented on graphics.lua
> +              switch = "flash"
While the flash could be put in the same row as the normal sprite, I'm not sure what you mean by the flickering, it's not swapping between matched and flash, the flickering is just the flash animation itself, the part that swaps it every frame is not there, it just stays on flash until the flash timer is up. 
If you mean in terms of not making the animation limited to when the flash ends, I can see it.

2024-04-21 19:28 UTC, Endaris commented on graphics.lua
> +              switch = "flash"
I was meaning this more in the way that the pre-conceived notion of using a flash is not the only way to signify to the player that the panels have matched.
The distinction between `FLASH` and `FACE` for the different parts of the existing matched animations is merely a construct derived from how TA animates this but it is not a functional part of the game physics so to me it seemed imaginable that someone may want to merge them into the same animation although I suppose with the level dependent differences in duration that may actually turn out difficult in practice so feel free to ignore that suggestions.

2024-04-21 20:05 UTC, DonavinDraws commented on config.lua
> +    panels                     	  = {}, -- setup later in panel init
I'll revert it, also I think the reason it was crashing for you was because I forgot to do a type a check in panel_init, cuz I thought I had it setup so it could coorrect old saves. For the community thing, I said that I was trying this in the modding channel and the only response I got was someone saying they really wanted it, so idk I wasn't really getting a response.

2024-04-22 20:39 UTC, Endaris commented on .gitignore
The usual idea of a local .gitignore file is that everyone has their individual set of files they ignore, e.g. project specific notes that shouldn't be version controlled.
So basically same problem as before, by adding it to version control, it overwrites the .gitignore anyone else might have added.
Please remove it from version control in your branch, you can avoid it being considered by git at all by adding it to your .gitignore file.

2024-04-22 20:49 UTC, DonavinDraws commented on .gitignore
there

2024-05-26 13:30 UTC, Endaris commented
As communicated on discord, I made a basic implementation that keeps panel draw read-only and removes the drawing from engine code to make sure any future changes have no impact on the engine.
I definitely referenced some things done here to make my own implementation do things right from the start so still, thanks a lot for your effort!
As the next step I'll focus on developing a solid technical approach for further configuration options related to animations on just one or two panel states and then we should hopefully be able to reuse it and expand it to other panel states.

2024-05-26 13:30 UTC, closed without merging