Modded Animation Scripting & Battle Sprite Loading + Signals
panel-attack/panel-attack pull request #1208
Opened 2024-07-03 15:27 UTC by DonavinDraws

2024-07-07 16:51 UTC, Endaris reviewed
Not a complete review but some general points regarding the signals and how the ability to animate is treated.

2024-07-07 16:51 UTC, Endaris commented on common/engine/Match.lua
> +    self:createSignal("matchStarted")
This one seems a little superfluous as effectively any match that is being created is also being started right away.
Or differently said, if the match was never started, there is also no stack that could be drawn. So the presence of a stack alone is indication enough that the match has started imo.
What use case did you imagine for this?

2024-07-07 16:51 UTC, Endaris commented on common/engine/Stack.lua
> +  end
I don't think communicating shake like this is right.
Generally speaking I'm entirely fine with any graphics stuff reading physics properties such as `shake_time` from the stack every frame. We don't incur any extra costs by the animation holding onto a reference to the stack and doing reads during its update.
More specifically though, I think in terms of a character sprite animation what you would be more interested in is when garbage dropped down and the shake value changes drastically (rather than staying 0 or decreasing by 1) as those would be the events when animators may want to reset the animation of being "attacked".
So in `Stack.onGarbageLand` or alternatively (possibly via a different signal) in `Stack.dropGarbage`.

2024-07-07 16:51 UTC, Endaris commented on client/src/mods/Character.lua
> +    self.battleSprite = nil -- AnimatedSprite | will be skipped if there is no sprite provided (Wouls like to get default sprites in the future)
As mentioned in earlier messages, I don't agree with the ability to provide animations for characters to default to a battle sprite.
If modders want to use other animations they should be able to.
One thing I could imagine as a rather uncreative person is adding effects around the stack's frame.
As such I would very much prefer it if this was rather named something like `battleAnimations`.

2024-07-07 16:51 UTC, Endaris commented on client/src/mods/Character.lua
> +  "battle"
Animations shouldn't be restricted to a single image.
Instead, the animation script should be read to get a list of used images and then these images get loaded as part of the full load.

2024-07-07 16:51 UTC, Endaris commented on client/src/mods/Character.lua
> +function Character:drawBattleSprite(stackNumber, x, y, scale)
Rename to `drawBattleAnimation`

2024-07-07 17:10 UTC, DonavinDraws commented on common/engine/Match.lua
> +    self:createSignal("matchStarted")
Intro Animations  during the countdown, but I guess I could also have battle sprites default to the intro animation

2024-07-07 17:17 UTC, DonavinDraws commented on common/engine/Stack.lua
> +  end
ok yeah, I was worried about the efficiency of calling signals every frame, the formatting of other signals looked like that was to be avoided, which is why I was struggling to find the right places to put these.

2024-07-07 17:21 UTC, DonavinDraws commented on client/src/mods/Character.lua
> +  "battle"
I was also heavily debating on having each animation use its own image, like the signal thing I assumed it was bad for efficiency or something. I can put separate image loading in.

2024-07-07 17:53 UTC, Endaris commented on common/engine/Stack.lua
> +  end
Neither `onGarbageLand` nor `dropGarbage` are being run every frame.
I think in general we don't want signals to be emitted every frame. But the reason is not really performance, more that it would defeat the purpose a bit. If we need information every frame we can just read the properties from the stack.
Signals are more to communicate events that are not immediately obvious from reading the stack.
Any performance cost would mainly be incurred by the callbacks you attach to the signal, not really the signal being emitted itself.

2024-07-07 18:18 UTC, DonavinDraws commented on common/engine/Stack.lua
> +  end
Oh, ok I see now. also I wanted to note that the reason I did that was cuz from what I've gathered, shaking seems to take priority over other animations, so I wanted to check when it both started and ended without having to reference the stack itself, but I can simplify it.

2024-07-08 02:55 UTC, Shosoul requested changes

2024-07-08 02:55 UTC, Shosoul commented on client/assets/default_data/characters/blargg/battle_anim.txt
I suggest we put this into a JSON format instead, since JSON is more universal and easily read and that way we won't have to worry about whitespace and stuff.

2024-07-08 02:55 UTC, Shosoul commented on client/assets/default_data/characters/blargg/battle.png
Worth discussing further, but I hesitate to add more Nintendo assets since we intend on getting rid of them.

2024-07-08 02:59 UTC, Shosoul commented on client/assets/default_data/characters/blargg/battle_anim.txt
I also would recommend hardcoding in the filename for easier interchangability

2024-07-08 09:01 UTC, Endaris commented on client/assets/default_data/characters/blargg/battle.png
I don't think there is a significant difference between having 100 nintendo assets or 120.
If they strike they strike.
That being said, I have discussed this with Donavin in advance and this PR only gets merged if it reasonably contributes to the goal of #597 by implementing a generic animation system that can react to ingame events.
If people can use this generic system to add battle sprites to nintendo characters, no reason to keep them from doing so.

2024-07-08 09:05 UTC, Endaris commented on client/assets/default_data/characters/blargg/battle_anim.txt
This is mostly not a json because I asked tgis to not be a json
json is a great format for serialization and reading but imo it blows for writing.
The goal of this file is to provide custom graphics scripting functionality and using json would unnecessarily restrict the feature set we can add later without things turning into a massive hassle, e.g. control flows, non-animation loops etc. would be horrible to express in json.

2024-11-10 11:43 UTC, Endaris commented
Closing for now so I have it's a bit easier to track for me what I still have to do for moving.
We'll revisit this in december as discussed.

2024-11-10 11:43 UTC, closed without merging