Removed love.touchpressed
panel-attack/panel-attack pull request #284
Opened 2021-11-19 03:15 UTC by C-Kudo

Removed touchpressed which caused unintentional same-frame double-tapping on touch devices due to sharing an event trigger with love.mousepressed.

2021-11-19 03:24 UTC, Shosoul requested changes

2021-11-19 03:24 UTC, Shosoul commented on click_menu.lua
> -function love.touchpressed(id, x, y, dx, dy, pressure)
Wouldn't this just make touch presses not work whatsoever? I'm not entirely sure that this is the reason why it's not working.

2021-11-19 05:20 UTC, JamesVanBoxtel commented on click_menu.lua
> -function love.touchpressed(id, x, y, dx, dy, pressure)
I too was confused by this, finally did a google search that found results. Someone mentions " But for convenience's sake, the mouse events are mapped to the first touch input, so you can handle single touch the same way you handle a mouse. "

C-Kudo can we add a comment to that affect up in love.mousepressed so we don't make this mistake again in the future?

2021-11-19 18:27 UTC, C-Kudo commented on click_menu.lua
> -function love.touchpressed(id, x, y, dx, dy, pressure)
Sure, it's definitely a little unintuitive because of the function names so we can make that a little more explicit. In short, touch presses still call mousepressed so it covers all our (current) needs.

2021-11-19 22:42 UTC, Shosoul requested changes
This way if we ever want to use touches in a different way or we change up the touch menu, we don't have to re-write the code for it.

2021-11-19 22:42 UTC, Shosoul commented on click_menu.lua
```suggestion

-- Handle a touch press
function love.touchpressed(id, x, y, dx, dy, pressure)
  local _x, _y = transform_coordinates(x, y)
  --click_or_tap(_x, _y, {id = id, x = _x, y = _y, dx = dx, dy = dy, pressure = pressure})
end
```

2021-11-19 22:42 UTC, Shosoul commented on click_menu.lua
> +-- Handle a mouse or touch press
```suggestion
-- Handle a mouse press
```

2021-11-19 22:42 UTC, Shosoul commented on click_menu.lua
> +function click_or_tap(x, y)
```suggestion
function click_or_tap(x, y, touchpress)
```

2021-11-20 00:52 UTC, JamesVanBoxtel commented on click_menu.lua
I wouldn't suggest adding a method just for the future, wasted code. At the very least it should be commented out and have the comment from above if you do that.

2021-11-20 02:43 UTC, Shosoul commented on click_menu.lua
But that's exactly what this is, it's commenting out code.

2021-11-20 05:05 UTC, JamesVanBoxtel commented on click_menu.lua
Yeah but the whole method should be commented out.

2021-11-20 06:16 UTC, Shosoul commented on click_menu.lua
Sure, sounds good. Fixed it

2021-11-20 08:01 UTC, C-Kudo commented on click_menu.lua
> +-- Handle a mouse or touch press
Doesn't this just add back the confusion we had the first discussion over? mousepressed does effectively handle touch presses too (even if that is the result of basically all touch-compatible collective OSes treating touch presses as mouse presses). Leaving that out is asking for this very bug to get reintroduced.

2021-11-20 08:38 UTC, Shosoul commented on click_menu.lua
> +-- Handle a mouse or touch press
Sure ig

2021-11-20 18:06 UTC, Shosoul approved these changes

2021-11-20 18:16 UTC, merged