Table functions
panel-attack/panel-attack pull request #412
Opened 2022-02-06 06:48 UTC by Endaris

Provides extensions to the table class in a new file table_util.
Migrated, deleted and/or renamed various functions in util.lua related to tables.
Added new file table_util to guarantee the basic functionality of the methods (as most of them are still unused right now). I do intend to use all unused ones for the computerPlayer branch.

2022-02-06 10:45 UTC, Shosoul commented
Interesting! Will look at tomorrow.

2022-02-06 19:41 UTC, JamesVanBoxtel commented on table_util.lua
> +function table.map(tab, func)
I believe table.mapDict will do everything table.map does, so might as well make them one. No need to guarantee the map happens in a particular order as long as the keys are right, and that makes it easier to not think about which one to use.

2022-02-06 19:41 UTC, JamesVanBoxtel commented on table_util.lua
> +        if filter(tab[i]) then
here you should use pairs() and insert using the key, that way will work for dictionaries and arrays

2022-02-06 19:41 UTC, JamesVanBoxtel commented on table_util.lua
> +function table.any(tab, condition)
Again you should use pairs() also maybe name it "containsWhere" or something? any implies it will return any object in the collection

2022-02-06 19:41 UTC, JamesVanBoxtel commented on table_util.lua
> +function table.all(tab, condition)
maybe "allSatisfyCondition" or something? also use pairs here

2022-02-06 19:41 UTC, JamesVanBoxtel commented on table_util.lua
> +function table.appendRange(list, tab)
Ideally this would work with dictionaries too. Range implies only a certain range would be inserted, probably "appendAll" or "appendList" would be fine

2022-02-06 19:41 UTC, JamesVanBoxtel commented on table_util.lua
> +function table.insertRange(list, position, tab)
"insertListAt" or something?

2022-02-06 19:41 UTC, JamesVanBoxtel commented on table_util.lua
> +function table.getRandomElement(tab)
Maybe we should assert this is a list? #tab == 0 or tab[1] ~= nil

2022-02-06 19:41 UTC, JamesVanBoxtel commented on table_util_tests.lua
> +    print("Passed test testTableMap")
We should use the "logger" here at a very detailed level. maybe logger.trace

2022-02-06 19:41 UTC, JamesVanBoxtel commented on table_util_tests.lua
> +local function testTableFilter()
Can you add tests for dictionaries too (Data that has a non integer key for the topmost table)

2022-02-07 00:28 UTC, Endaris commented on table_util.lua
> +function table.getIterator(tab)
It isn't, I'm just not used to this way of iterating over elements in a collection where I intentionally throw away return values the iterator gives me, LOL.
Going to remove this.

2022-02-07 00:37 UTC, Endaris commented on table_util.lua
> +function table.map(tab, func)
Yeah, you're right, I didn't look too closely at this since I ported both over from util.lua although it seems mapDict was unused anyway.

2022-02-07 02:03 UTC, Shosoul requested changes

2022-02-07 02:03 UTC, Shosoul commented on mainloop.lua
> +  print(TESTS_ENABLED)
Should we use the logger here?

2022-02-07 02:06 UTC, Endaris commented on mainloop.lua
> +  print(TESTS_ENABLED)
Oh, good catch, i'm just going to axe this
Only added this because the tests weren't executing since I had to reinsert the debugger setup at the start of main.lua

2022-02-07 02:33 UTC, Endaris commented on table_util.lua
> +        if filter(tab[i]) then
When inserting using the key, a filtered sequential list will have jumbled non-continuous indices as a result so this is not going to work right away. I'll need to check whether the table is a sequentially indexed table or not to determine whether the values should be added based on the key or at the end of the sequence.

Personally I think filtering dictionaries for values rarely makes sense without specifying the key, because the keys usually present more something like attribute names so it would normally only make sense to filter inside the table that represents the value to a key.

2022-02-07 03:28 UTC, Endaris commented on table_util.lua
> +function table.getRandomElement(tab)
Instead of asserting this, I added a condition for this, so that it can grab a random element from a dictionary as well (whether that makes sense or not is debatable.

2022-02-07 03:29 UTC, Endaris commented on table_util.lua
> +function table.all(tab, condition)
renamed to trueForAll and using pairs now

2022-02-07 03:29 UTC, Endaris commented on table_util.lua
> +function table.any(tab, condition)
renamed to trueForAny and using pairs now

2022-02-07 03:31 UTC, Endaris commented on table_util.lua
> +function table.appendIfNotExists(tab, element)
If possible I'd like to chicken out of this until a later point in time since I don't have a clue (yet) how hashsets work internally.

2022-02-07 03:33 UTC, Endaris commented on table_util.lua
> +function table.appendRange(list, tab)
Supports dictionaries now, renamed to "appendTo"

2022-02-07 03:53 UTC, Endaris commented on table_util_tests.lua
> +local function testTableFilter()
Added more tests, tell me if you'd like to see any more for now.

2022-02-07 04:44 UTC, JamesVanBoxtel commented on table_util.lua
> +        if filter(tab[i]) then
Fair enough, I would at least assert that the table is empty or has index 1 then though so we don't accidentally use it on a dictionary

2022-02-07 05:32 UTC, JamesVanBoxtel commented
Tested and looks good overall, just need to cleanup the separate out the dictionary append into its own method

2022-02-07 05:53 UTC, Endaris commented on table_util.lua
> +function table.appendRange(list, tab)
Aaaaand doesn't support dictionaries anymore.
The test case for the key collision error kept making the debugger stop on that error despite the pcall wrap.
In general the use case is quite shady for dictionaries, the method is not being used currently and we strive to use syn.tax instead of syn["tax"] anyway.
Talked this through with Jam, revisiting when we actually find a realistic use case for this.

2022-02-07 06:00 UTC, Endaris commented on table_util.lua
> +        if filter(tab[i]) then
Yep, that's what we're doing, method supports both lists and dictionaries with different loops depending on whether the table is determined to be a list or not.

2022-02-07 06:56 UTC, Shosoul requested changes
Code should be indented with two spaces width instead of four.

2022-02-07 06:58 UTC, Shosoul commented
Otherwise, looks good, I think.

2022-02-07 07:59 UTC, Shosoul submitted a review, later dismissed

2022-02-08 02:31 UTC, Endaris commented
i don't even know

2022-02-08 09:46 UTC, Endaris commented
Reverted that weird merge from computerPlayer

2022-02-08 10:19 UTC, Shosoul approved these changes
Praise the lord for squash commits.

2022-02-09 05:02 UTC, JamesVanBoxtel approved these changes

2022-02-09 05:03 UTC, merged