Illegal combo garbage
panel-attack/panel-attack pull request #449
Opened 2022-03-04 08:10 UTC by Shosoul

2022-03-04 08:39 UTC, Shosoul commented
Soon, I'll have to make the different shapes possible. But otherwise, here's something I can do for now.

2022-03-04 23:25 UTC, Shosoul commented
Renamed to "Illegal Garbage", this PR now allows all types of illegal garbage to be used.

2022-03-07 04:43 UTC, JamesVanBoxtel requested changes
Haven't got to fully review this yet but started testing and looking through it. Found what I think is a break but overall its looking good

2022-03-07 04:43 UTC, JamesVanBoxtel commented on engine.lua
> +        if metal_count > 3 then
I noticed when I made a 6 combo with 3 shock blocks and 3 normal blocks I didn't get a metal garbage, just a 5 wide block. Pretty sure thats a break.

2022-03-08 00:30 UTC, Shosoul commented on engine.lua
> +        if metal_count > 3 then
What would normally result from this?

2022-03-08 01:28 UTC, Shosoul commented
Should be good now.

2022-03-08 03:52 UTC, JamesVanBoxtel approved these changes

2022-03-08 03:54 UTC, merged