Implement love.run for better performance
panel-attack/panel-attack pull request #471
Opened 2022-03-16 04:39 UTC by JamesVanBoxtel

Garbage collection was causing major spikes in cpu which reduced performance and contributed to input lag.

To help with this we implement our own love.run similar to the default.

What is different is we only update / render at 60fps and we garbage collect on the other updates. This means we have less garbage build up which reduces spikes.

Other changes include
Debug options menu for inducing lag in replays and vs online
Performance logger for tracking this in the future
Vsync is now always off to support this feature

2022-03-16 20:24 UTC, Shosoul commented
I probably would not commit the profiler, now that I've looked at this more.

2022-03-16 20:34 UTC, Shosoul commented
If we collect garbage manually, we can turn off the automatic one with `collectgarbage("stop")`

2022-03-16 21:04 UTC, Shosoul commented
Does also seem to cause weird graphics effects, such as black squares when navigating the menu. Really bold face example of this is trying to login to the server when someone with your name is in the lobby, and when entering mid-match to spectate someone.

2022-03-17 04:55 UTC, Shosoul requested changes
In addition, now that we manually collect garbage ourselves, I think we could also disable the automatic garbage collector through the use of  `collectgarbage("stop")`.

2022-03-17 04:55 UTC, Shosoul commented on main.lua
> +PROFILER = require("jprof")
I believe we should not include the profiler in the commit. Or, at least, we keep it for now, but remove it entirely when we merge it into the beta branch.

2022-03-17 04:55 UTC, Shosoul commented on options.lua
> +local function debug_menu(button_idx)
IMO, we should put the keep the debug menu in the general menu. Keeping this menu itself, of course, but make it accessible from the general menu instead of being standalone.

2022-03-17 05:00 UTC, Shosoul commented
Client also crashes immediately upon leaving in the middle of a match that it was spectating.
```
main.lua:106: mainloop.lua:403: attempt to index field 'match' (a nil value)
stack traceback:
mainloop.lua: in function 'f'
mainloop.lua:101: in function 'variable_step'
mainloop.lua:401: in function 'func'
mainloop.lua:88: in function <mainloop.lua:29>```

2022-03-19 05:06 UTC, JamesVanBoxtel commented
Abandoning this for now as we haven't actually proved this fixes the problem.

2022-03-19 05:06 UTC, closed without merging