Fix critical chain stop time
panel-attack/panel-attack pull request #477
Opened 2022-03-21 02:46 UTC by JamesVanBoxtel

There was a bug causing it to be inaccurate for chains greater than 5

2022-03-21 02:53 UTC, Shosoul commented on engine.lua
> +          stop_time = -8 * self.level + 168 + (length - 1) * (-2 * self.level + 22)
I'm just double-checking, since this is an actual engine change, that we are still supposed to subtract one from the length?

2022-03-24 04:00 UTC, Shosoul requested changes

2022-03-24 06:18 UTC, Endaris commented
Since we already had some heated discussion, maybe we want to actually consider using > 5 and 6 because the way the stop time caps here reminds of a <= vs < bug.
The important thing to fix in my opinion is actually capping the stop time and having a clean cut off instead of the weird jump right before the cutoff already achieves the intent of this thing.

2022-03-25 03:35 UTC, Shosoul approved these changes

2022-03-25 03:36 UTC, JamesVanBoxtel commented
I think in practice its so little difference that it just makes sense to emulate what TA did
we haven't changed any other stop time values to make them "better"
so why diverge here even though its weird.

if we decide later to change values to make the game play "better" we can revisit stuff like this.

2022-03-28 02:47 UTC, merged