Remove Health Replenishment from Downstacking when Topped Out
panel-attack/panel-attack pull request #487
Opened 2022-03-30 23:03 UTC by Shosoul

Or, more accurately, described as stop time. This changes it to be true to Tetris Attack.

2022-03-31 04:14 UTC, JamesVanBoxtel requested changes

2022-03-31 04:14 UTC, JamesVanBoxtel commented on engine.lua
> +    local has_life_time = self.pre_stop_time > 0 or self.stop_time > 0 or self.shake_time > 0
I don't think this portion of the change makes sense from a game play perspective. 

Recommend we only take the portion of the patch that doesn't allow resetting health from downstacking garbage.

2022-03-31 04:35 UTC, Shosoul commented on engine.lua
> +    local has_life_time = self.pre_stop_time > 0 or self.stop_time > 0 or self.shake_time > 0
Do you think it would be best to put this to a survey?

2022-03-31 04:47 UTC, JamesVanBoxtel commented on engine.lua
> +    local has_life_time = self.pre_stop_time > 0 or self.stop_time > 0 or self.shake_time > 0
I don't think it is really a good idea even if a survey agreed with it. But if Jon or one of the other original authors / maintainers agreed we should do it then I could accept it if the survey agreed too. 

But I really feel like we are copying a bug or a bad game mechanic if we do this.

2022-03-31 04:49 UTC, Shosoul commented on engine.lua
> +    local has_life_time = self.pre_stop_time > 0 or self.stop_time > 0 or self.shake_time > 0
Let's do it this way: The survey should have more than 3/5ths of voters in favor for this change. In the event that we have exactly 3/5ths of a ratio, we do not implement this change.

2022-04-12 17:39 UTC, Shosoul commented on engine.lua
> +    local has_life_time = self.pre_stop_time > 0 or self.stop_time > 0 or self.shake_time > 0
Works for me. I'll make a change to this draft to reflect that. I would also like to document this "health boost" extensively to show the difference between panel attack and tetris attack.

2022-04-13 07:02 UTC, Shosoul commented
I still need to push documentation changes, but the engine itself now works as we want it.

2022-04-15 12:43 UTC, merged