Refactor select screen
panel-attack/panel-attack pull request #493
Opened 2022-04-14 02:47 UTC by Endaris

Refactoring of select screen

2022-04-15 16:36 UTC, Shosoul commented
Would it be easier to put the select screen graphics in the same file? Maybe keep the two classes in the same file since select screen graphics won't be used in any other file.

2022-04-25 23:34 UTC, Endaris commented
I made a subfolder to keep it separated because I believe that it is in general bad practice to have files having hundreds or thousands lines of code and I think keeping them separate if only for orientation is better.

2022-04-25 23:40 UTC, Endaris commented
In general, the main issue remaining with this PR is that it adds an intermediate layer with the select screen class, not making the returning of callback functions directly available anymore.
While trying to debug this, I found that the menuing mainloop part 
```Lua
while true do
    leftover_time = 1 / 120 -- prevents any left over time from getting big transitioning between menus
---@diagnostic disable-next-line: redundant-parameter
    func, arg = func(unpack(arg or {}))
    collectgarbage("collect")
    logger.trace("Transitioning to next fmainloop function")
  end```
is quite cryptic and difficult to debug because Lua does not expose which function it is actually calling (we only get the pointer and I wasn't very successful with `debug.getinfo`) and through the double unpack run both here and in main_dumb_transition / game_over_transition it becomes a bit intransparent what is actually happening here.

Besides that it also needs testing in vs mode with both playing and spectating which is currently difficult to orchestrate as it is based on the alpha version so this will have to wait until telegraph hits the stable server.

2022-04-26 01:37 UTC, Shosoul commented
Could we make the select screen functions local instead of global? One other reason I think it would be nice to keep it in one file is so that the functions don't have to be global.

2022-04-26 01:53 UTC, Endaris commented
I honestly had that idea as well already but the issue is that from what I know you can only make a function *either* local *or* class functions.
Both kinds ensure some kind of encapsulation of the methods that aren't relevant to the rest of the game. Personally I prefer the class encapsulation because with local functions you either need to do functions inside functions - which is part what I tried to get rid of here because the resulting indenting makes things difficult to divide - or you need to keep explicitly passing the state object in and out all the time to make sure you can access the relevant values.
So if anything the latter but personally I don't see the benefit very much.

I think an alternative might be making the class itself local but we still need to access it from the outside somehow so I'm not sure if that actually has a chance to work.

2022-04-26 01:57 UTC, Shosoul commented
I'm lean towards combining the files because local functions are faster than global ones, which is why I believe it's important to make these local.

2022-05-01 17:25 UTC, Endaris commented
I used the event yesterday to test the spectate side of net vs a bit and was able to iron out some stuff.
Right now it works fine if you join a match, however the automove to the next match does not seem to work and we're getting a disparity between screens and the state indicated by server messages.
I'll continue taking care of these last issues once alpha hits beta / stable so that I don't have to go out of my way to find matches to spectate.

2022-06-13 07:25 UTC, Endaris commented
1 player modes and spectating are now fully functional (from what I can tell)
When playing 2p vs there is still an update problem that keeps the opponent's character, stage and ready state from being loaded, will hopefully be able to work that out tomorrow.

2022-06-15 00:31 UTC, Endaris commented
Was able to finish a FT20 against Tai on this branch without a hitch, I think the only thing that is still "broken" is that while spectating the textbox during the dumb transition into the next game is empty for some reason.

2022-06-15 05:31 UTC, Endaris commented
> Was able to finish a FT20 against Tai on this branch without a hitch, I think the only thing that is still "broken" is that while synchronizing upon starting to spectate a running match the textbox during the dumb transition into the next game is empty for some reason.

Actually misinterpreted this because there is this empty black box here that actually exists on beta as well, I just wasn't able to see it on my beta client cause my theme has a black background in that area:
![grafik](https://user-images.githubusercontent.com/22120694/173745995-ef076960-7dc4-4102-9741-9ee84b0a660b.png)
The text itself is getting briefly rendered as per usual (just much further up than I expected, likely due to the different main menu offset between themes) so this actually works

2022-06-16 03:00 UTC, JamesVanBoxtel commented
Overall this seems to be working well, but the stage selector seems broken to me.

2022-06-16 06:38 UTC, Endaris commented
Did some changes based on Jam's feedback, one that may be controversial is that I added two new globals to the config, `fallbackCharacter` and `fallbackStage` that are on a default of random.
I did that because the fallbackAsset logic already existed prior to my refactor (albeit unused) and the alternative would be axing it due to my changes to `refreshBasedOnOwnMods` which is also being used for playing replays.
These naturally still lack UI to configure them through PA but between having and not having I think that's better.
Let me know what you think!

2022-06-16 06:59 UTC, Shosoul requested changes
Before I start, this is an impressive piece of work you've done. I thank you for it, you've done a really good job.

I've noticed a couple things so far:
Normally, there is text below the menu indicating how many pages of characters there are, but it's missing.
![screenshot_v046-2022-06-16-06-53-22](https://user-images.githubusercontent.com/18148657/174009939-1d5d3a87-54ae-4984-b017-bdb8c4a3bf64.png)

Also, I am no longer able to scroll infinitely through stages, it doesn't loop back to the beginning of the list anymore if I go to the end of it.

Haven't fully formed my opinion on the globals yet, but we should generally try to avoid adding globals whenever we can.

I'm gonna go check out the code more in depth now, looks like the rest of it from firing up the game looks good. I'll also probably test a bit online tomorrow.

2022-06-16 07:19 UTC, Shosoul commented
The "random" stage option is missing as well.

2022-06-16 07:23 UTC, Shosoul commented
I get this upon trying to start a game in training mode.
![image](https://user-images.githubusercontent.com/18148657/174015227-33c9191d-f9b5-4170-bc9d-f56f55979b89.png)

2022-06-17 04:32 UTC, JamesVanBoxtel reviewed
Also we need to look into the latency / spectator timing feeling different with this branch

2022-06-17 04:32 UTC, JamesVanBoxtel commented on table_util.lua
> +-- returns the
```suggestion
-- returns the key for the given value, key is random if value occurs multiple times
```

2022-06-17 04:32 UTC, JamesVanBoxtel commented on globals.lua
> +  fallbackCharacter             = random_character_special_value,
Since these aren't customizable right now and we probably want to think about the design of this, I'd recommend we just hardcode the random special value in their reference sites instead of adding this to config.

2022-06-17 04:52 UTC, Endaris commented
There is a netplay only issue where the selected character is not actually being used and instead randomized, probably introduced that with the latest reworks for mod refreshing.

2022-06-17 05:43 UTC, Endaris commented
> Also we need to look into the latency / spectator timing feeling different with this branch

Jam and I tested this and seems like an issue with backwards compatibility, not a general issue.
With both players on this branch, latency is great, between this branch and beta or stable not so much.
Setting the transition into vs from 60 to 30 is an attempt to bring the setup processes of the builds closer together, will have to test more to see if this actually solves the problem.

2022-06-17 22:31 UTC, Endaris commented
Latency between this branch and stable/beta is still bad even after changing transition time.

2022-06-18 00:15 UTC, Endaris commented
From what I can tell, the main issue between the branches is that the refactorSelectScreen branch receives the initial input of the opponent a good deal faster than beta.
Adding a `do_messages` and `print(server_queue:to_string())` right before the transition into `main_net_vs` also indicated that there are no server messages lingering around at that point in time that would explain why the initial input message is received so early in comparison to beta.

On beta:
```
Receiving message: 
{"match_start":true,"stage":"endaris_umineko_u2_nighteyes","ranked":false,"player_settings":{"level":10,"character_display_name":"Ashley","character":"meido_ashley","player_number":1,"panels_dir":"panelhd_basic_mizunoketsuban"},"seed":5660544,"opponent_settings":{"level":10,"character_display_name":"Kurtupo","character":"pokemon_trainer_kurtupo","player_number":2,"panels_dir":"pacci"}}
Sending controls: 
 A at stack.clock: 0
Aborted a send_control
Aborted a send_control
Aborted a send_control
Aborted a send_control
Aborted a send_control
Aborted a send_control
Aborted a send_control
Aborted a send_control
Aborted a send_control
Aborted a send_control
Aborted a send_control
Aborted a send_control
Aborted a send_control
Aborted a send_control
Aborted a send_control
Aborted a send_control
Receiving message: 
{"I":"A"}
Sending controls: 
 A at stack.clock: 1
Sending controls: 
 A at stack.clock: 2
Sending controls: 
 A at stack.clock: 3
Sending controls: 
 A at stack.clock: 4
Sending controls: 
 A at stack.clock: 5
Sending controls: 
 A at stack.clock: 6
Sending controls: 
 A at stack.clock: 7
Sending controls: 
 A at stack.clock: 8
Sending controls: 
 A at stack.clock: 9
Sending controls: 
 A at stack.clock: 10
Sending controls: 
 A at stack.clock: 11
Sending controls: 
 A at stack.clock: 12
Sending controls: 
 A at stack.clock: 13
Sending controls: 
 A at stack.clock: 14
Sending controls: 
 A at stack.clock: 15
Sending controls: 
 A at stack.clock: 16
Sending controls: 
 A at stack.clock: 17
Receiving message: 
{"I":"A"}
```

on refactorSelectScreen:
```
{"seed":3891284,"opponent_settings":{"player_number":1,"panels_dir":"pacci","level":10,"character":"pokemon_trainer_kurtupo","character_display_name":"Kurtupo"},"match_start":true,"stage":"endaris_umineko_dir","player_settings":{"level":10,"player_number":2,"panels_dir":"panelhd_basic_mizunoketsuban","character":"meido_ashley"},"ranked":false}
QUEUE: { ["empties"] = 0,["first"] = 0,["last"] = -1,["data"] = { } ,} 
Sending controls: 
 A at stack.clock: 0
Receiving message: 
{"I":"A"}
Sending controls: 
 A at stack.clock: 1
Sending controls: 
 A at stack.clock: 2
Sending controls: 
 A at stack.clock: 3
Sending controls: 
 A at stack.clock: 4
Sending controls: 
 A at stack.clock: 5
Sending controls: 
 A at stack.clock: 6
Sending controls: 
 A at stack.clock: 7
Sending controls: 
 A at stack.clock: 8
Sending controls: 
 A at stack.clock: 9
Sending controls: 
 A at stack.clock: 10
Sending controls: 
 A at stack.clock: 11
Sending controls: 
 A at stack.clock: 12
Sending controls: 
 A at stack.clock: 13
Sending controls: 
 A at stack.clock: 14
Sending controls: 
 A at stack.clock: 15
Sending controls: 
 A at stack.clock: 16
Sending controls: 
 A at stack.clock: 17
Sending controls: 
 A at stack.clock: 18
Sending controls: 
 A at stack.clock: 19
Sending controls: 
 A at stack.clock: 20
Sending controls: 
 A at stack.clock: 21
Sending controls: 
 A at stack.clock: 22
Sending controls: 
 A at stack.clock: 23
Sending controls: 
 A at stack.clock: 24
Sending controls: 
 A at stack.clock: 25
Sending controls: 
 A at stack.clock: 26
Sending controls: 
 A at stack.clock: 27
Sending controls: 
 A at stack.clock: 28
Sending controls: 
 A at stack.clock: 29
Sending controls: 
 A at stack.clock: 30
Sending controls: 
 A at stack.clock: 31
Sending controls: 
 A at stack.clock: 32
Sending controls: 
 A at stack.clock: 33
Receiving message: 
{"I":"A"}
```

(for the gross latency, note that I get about 15 frames more latency when playing online against myself compared to playing against others)

2022-06-18 00:44 UTC, Endaris commented
Instead of only waiting for the first message, waiting for the first two messages seems to lower the latency greatly for the person on the refactorSelectScreen branch but equally increases the latency of the person on the beta branch so that doesn't seem to be the perfect solution either.

2022-06-28 04:39 UTC, JamesVanBoxtel approved these changes

2022-06-28 21:50 UTC, Shosoul approved these changes

2022-06-28 21:50 UTC, merged