Custom Fonts
panel-attack/panel-attack pull request #500
Opened 2022-04-20 05:48 UTC by Shosoul

Adds custom fonts to the game.

2022-04-22 02:39 UTC, JamesVanBoxtel requested changes
I also noticed this doesn't work when you change languages so we should unify with that.

2022-04-22 02:39 UTC, JamesVanBoxtel commented on theme.lua
> +    set_global_font("themes/" .. config.theme .. "/font.ttf", 12)
for some fonts this is actually pushing the text off screen

2022-04-22 02:39 UTC, JamesVanBoxtel commented on readme_themes.txt
> +- "font": add this file to customize the font
Recommend we allow setting the file name in the theme so the font can still be recognized by name in the file browser. It would also be nice to be able to set the font size

2022-04-24 07:46 UTC, Shosoul commented
Fixed

2022-04-26 01:44 UTC, Shosoul commented on readme_themes.txt
> +- "font": add this file to customize the font
Now a thing

2022-04-26 01:45 UTC, Shosoul commented on theme.lua
> +    set_global_font("themes/" .. config.theme .. "/font.ttf", 12)
I added font size, so people can fix this on their own.

2022-05-01 04:12 UTC, JamesVanBoxtel approved these changes

2022-05-01 04:12 UTC, JamesVanBoxtel commented on readme_themes.txt
> +
Can you add documentation about the font size as well?

2022-05-01 04:12 UTC, JamesVanBoxtel commented on readme_themes.txt
> +
Can you add documentation about the font size as well?

2022-05-03 03:00 UTC, Shosoul commented on options.lua
> +      localization:set_language(language_choices[language_number])
Done.

2022-05-03 03:02 UTC, Shosoul commented on readme_themes.txt
> +
done

2022-05-03 04:03 UTC, merged