Manage training memory
panel-attack/panel-attack pull request #552
Opened 2022-06-12 04:21 UTC by Shosoul

Make it so that garbage does not infinitely queue up by default, which caused performance issues.

2022-06-12 05:08 UTC, Endaris requested changes

2022-06-12 05:08 UTC, Endaris commented on AttackEngine.lua
> +    end
I don't think this needs to be ipairs?
Just use a for with an iteration variable, better performance.
Aside from that a question regarding counting up garbageCount:
In which case is a pattern a chain that does not end a chain? Is it even possible that this condition is ever false?
Maybe I'm missing something there but otherwise you could simply set garbageCount to `table.len(self.attackPatterns)`

2022-06-12 05:08 UTC, Endaris commented on AttackEngine.lua
> +    for _, attackPattern in ipairs(self.attackPatterns) do
Same ipairs vs for i thing.

2022-06-12 17:04 UTC, Shosoul commented on AttackEngine.lua
> +    end
Yea, I could change it to make it better, I can do that when I get home. The reason for the if statement is because every step for chains counts as an individual attackPattern, but we only want to count the chain once, so I just count the end chain indicators and the combo garbage.

2022-06-12 17:06 UTC, Endaris commented on AttackEngine.lua
> +    end
Ah, in that case the name "attackPattern" is a bit misleading as each attackPattern is in fact not a pattern but rather a singulary attack. Probably worth to clean up with some renames there but I can understand if that blows up the scope of this fix.

2022-06-12 17:47 UTC, Shosoul commented on AttackEngine.lua
> +    end
We are probably gonna do a big cleanup soon so we can change the names during that probably

2022-06-14 04:45 UTC, JamesVanBoxtel commented
Just catching up on stuff. Can you explain what actually went wrong to cause the performance problems? Why does having too much garbage queued up cause major slowdowns?

2022-06-14 04:49 UTC, Shosoul commented
The after some time, the garbage queue would backlog so much garbage that the game would slow, and eventually cause fun errors like this:

```
main.lua:96: not enough memory

{ ["release_version"] = Unknown,
["operating_system"] = OS: Windows,
["love_version"] = 11.4.0,
["error"] = not enough memory,
["name"] = ShosoulDev,
["stack"] = stack traceback:
network.lua: in function 'send_controls'
match.lua:183: in function 'run'
mainloop.lua:476: in function 'f'
mainloop.lua:109: in function 'variable_step'
mainloop.lua:473: in function 'func'
mainloop.lua:96: in function <mainloop.lua:39>,
["engine_version"] = 046,
} 


Traceback

[love "callbacks.lua"]:228: in function 'handler'
[C]: in function 'error'
main.lua:96: in function 'update'
[love "callbacks.lua"]:162: in function <[love "callbacks.lua"]:144>
[C]: in function 'xpcall'
```

2022-06-14 04:50 UTC, JamesVanBoxtel commented
Did you ever get down to the bottom or what was using all the memory?

2022-06-14 04:51 UTC, Shosoul commented
Yes. There was literally just so much garbage being put in the garbage queue the game eventually struggled to process it all. It's simply the fact that there were thousands upon thousands of garbage blocks being queued.

2022-06-14 04:52 UTC, Shosoul commented
Which is what you would get if you survived for long enough. [Here is the start of the conversation in the discord bugs channel](https://ptb.discord.com/channels/196674532491132937/362093490538020864/985371770372645005).

2022-06-14 04:55 UTC, Shosoul commented
I have renamed this PR to a more accurate title.

2022-06-15 15:25 UTC, JamesVanBoxtel approved these changes

2022-06-15 19:03 UTC, merged