Save window state in config
panel-attack/panel-attack pull request #553
Opened 2022-06-12 18:59 UTC by Endaris

Solves #549 
While I was at it I also included true fullscreen support, meaning that by pressing Left Alt+Enter you now cycle through windowed, windowed borderless fullscreen and (exclusive) fullscreen.
I think using exclusive fullscreen may or may not be helpful for people on toasters like Zack.
Right now there is no perceivable difference between windowed borderless and exclusive fullscreen until you alt+tab so there should be a notification be displayed later on (#531)

Additionally I also reviewed the behaviour on first startup with regards to #549 because I felt it would be good if the game started in a workable size right away so the game will try to maximize itself now if there is no `conf.json` to be found. This is tracked in the new field `config.firstStartup` that we could utilize for future first startup shenanigans later on (e.g. directing them directly to the key configuration, maybe displaying a page that gives an overview what there is to discover, offering to enter the tutorial if they are new etc.)

I tested this on Windows and Linux Ubuntu, would be great if you could verify the functionality on Mac @JamesVanBoxtel

2022-06-12 19:33 UTC, Shosoul requested changes
I would personally avoid using exclusive desktop, per the reasons of the LOVE wiki:

> "In exclusive fullscreen mode, if a window size is used which does not match one of the monitor's supported display modes, the window will be resized to the next largest display mode.
Exclusive fullscreen mode is sometimes avoided by users because it can cause issues in some window managers and with multi-monitor setups. In OS X it prevents switching to a different program until fullscreen mode is exited. The "desktop" fullscreen mode generally avoids these issues."

I think we don't need a first startup variable yet, but I can go into that more once I get home from work.

2022-06-12 19:42 UTC, Endaris commented
For context, this is how PA starts without a config for me on Win10 which is why I added the first start up stuff:
![grafik](https://user-images.githubusercontent.com/22120694/173250442-ec8d9fb9-b11f-4e3d-a49b-ba998acd94f2.png)

2022-06-12 19:49 UTC, Endaris commented
> I would personally avoid using exclusive desktop, per the reasons of the LOVE wiki:

I'll search if there cases of love breaking things the moment you enable exclusive fullscreen or if the consequences are more indirect.
Cause by cycling through all three options, you don't need to use exclusive fullscreen if you don't want to. Just giving the option seems reasonable to me unless it easily breaks things because as mentioned, toasters might profit and the target audience exists.

2022-06-12 20:11 UTC, Endaris commented
> > I would personally avoid using exclusive desktop, per the reasons of the LOVE wiki:
> 
> I'll search if there cases of love breaking things the moment you enable exclusive fullscreen or if the consequences are more indirect. Cause by cycling through all three options, you don't need to use exclusive fullscreen if you don't want to. Just giving the option seems reasonable to me unless it easily breaks things because as mentioned, toasters might profit and the target audience exists.

Okay, I'll axe this part, somehow this worked perfectly fine *before* I added the first start up thing and even if I poll the available dimensions at the start, might add true windowed borderless instead though.

2022-07-09 05:06 UTC, JamesVanBoxtel commented
I believe I have implemented everything this did in #567 so I think we can close this.

2022-07-11 01:32 UTC, JamesVanBoxtel commented
To clarify more:

I believe this PR does the following:
Saves and restores width, height, and maximized state
Sets firstStartup which allows us to do extra things on startup
Maximizes on first run

Those are all done in #567 however it does it at love.conf time which makes it so the window only loads and positions once which makes it not animate and also makes it load faster. If we do need to do anything with first startup we can always track that when we load the config file, but I think based on these changes we don't need to do that for now.

The work done in this PR is instrumental in researching and developing that approach, which I think gets us to the best possible implementation.

2022-07-19 22:08 UTC, closed without merging