rewrote leaderboard loop using ipairs and set rank by username comparison
panel-attack/panel-attack pull request #560
Opened 2022-06-16 04:46 UTC by KattKit

## What

In this PR I rewrote the leader board loop that searches for the players ranks before displaying the report, and then picks the players rank based on their username

## Why

on inspection, the loop wasn't behaving as expected. so I rewrote it using `ipairs()` which is recommended for array iteration by lua's documentation. I also changed the condition for picking the rank to rely on the user_name as `is_you` data wasn't present in testing, and `is_you` looks needlessly intense for incoming data.

2022-06-16 07:10 UTC, Endaris reviewed
For properly indexed arrays we normally prefer iterating by index because it is faster and unlike `pairs`, `ipairs` has functionally no advantages over an indexed for loop.
Not a performance critical part here so it's fine by me.

See https://springrts.com/wiki/Lua_Performance#TEST_9:_for-loops for reference on loop performance.

2022-06-16 07:10 UTC, Endaris commented on mainloop.lua
> +        for key, value in ipairs(leaderboard_report) do
Personally I'm a sucker for readability, so instead of going with `key, value`, I'd name them after what they actually are, `rank` and `user`.

2022-06-16 15:23 UTC, JamesVanBoxtel commented
Tested and functionality works great.

2022-06-23 12:05 UTC, Shosoul requested changes
I would do what @Endaris suggested, then it's good to go imo

2022-06-23 12:05 UTC, Shosoul commented on mainloop.lua
> +        for key, value in ipairs(leaderboard_report) do
I second this!

2022-06-25 04:18 UTC, JamesVanBoxtel approved these changes

2022-06-25 04:18 UTC, JamesVanBoxtel commented on mainloop.lua
> +        for key, value in ipairs(leaderboard_report) do
```suggestion
        for rank = #leaderboard_report, 1, -1 do
          local user = leaderboard_report[rank]
          if user.user_name == config.name then
            my_rank = rank
```

2022-06-25 04:18 UTC, JamesVanBoxtel commented on mainloop.lua
> +          if value.user_name == config.name then
```suggestion
```

2022-06-25 04:18 UTC, JamesVanBoxtel commented on mainloop.lua
> +            my_rank = key
```suggestion
```

2022-06-25 04:21 UTC, Shosoul approved these changes

2022-06-25 04:21 UTC, merged