Modern Resolution Support
panel-attack/panel-attack pull request #567
Opened 2022-07-04 16:47 UTC by JamesVanBoxtel

The canvas will continue to be thought about as 1280 x 720
To add resolution support, we instead add higher resolution assets and fonts and scale the screen to 1.5 or 2 times scale.
We fix all the interpolation to use linear when scaling down and nearest neighbor when scaling up (to continue to support "pixel" looking art)
Also added support for retina displays
Note we don't use love's auto scaling dpi feature, as we want to do the same thing regardless of OS
Also fixed some hard coded numbers that could non pixel align things
Recalculate the scale when resizing the window
Cleaned up fonts and made them support high dpi
Fixed a few spots that assumed the scale of theme images
Updated the name of the cursor file so it doesn't imply player 1 and 2

2022-07-09 05:05 UTC, JamesVanBoxtel commented
I have tested this a lot and finished everything I can think of, think its ready for review.

2022-07-10 06:59 UTC, Endaris reviewed
Okay, so first of all I want to say that I'm not satisfied with how you handled this. I feel like it's disregarding my work to not even bother reviewing my PR and just slap a comment on it that - with all respect - reads like "I think this can be closed cause I did it better". I think the PR I did was functional and addressed immediate problems. All you do with this PR is integrate it into an even bigger PR that adds more complexity and features and is therefore harder to review. I think if possible PRs should be kept small and this is quite the opposite of it.

Onto the PR itself. 
First of all, there is clearly perceivable stuttering in the game when switching between game scale modes. Ideally the preview would not reload the entire theme immediately upon changing the selection but instead only reloads the assets on the current screen and then proceeds to reload the rest of the theme upon returning to the main menu, just like when you change your theme. Otherwise it creates a very unintuitive discrepance in the handling between the options.
Secondly I don't think the available options are transparent as to what they do. "auto" and "scaled" look identical for me, yet they are different options. If the unique options for selections aren't clear, the feature is hard to use. I don't even know a use-case in which I would want to use a Game Scale higher than 1 so what the higher scalings are for is quite the mystery for me, especially because I can already no longer see which panels are coming from the bottom even at a Game Scale of 1 unless I turn on fullscreen!

2022-07-10 06:59 UTC, Endaris commented on game.lua
> +  panels_init()
`characters_init()` and `stages_init()` should always be called upon reinitializing a theme because of differences in the characters.txt requiring refilling `characters_ids_for_current_theme` (analog for stages)

2022-07-10 06:59 UTC, Endaris commented on conf.lua
> +require("globals")
https://github.com/panel-attack/panel-attack/pull/569#discussion_r915444449

2022-07-10 06:59 UTC, Endaris commented on conf.lua
> +  readConfigFile(config)
https://github.com/panel-attack/panel-attack/pull/569#discussion_r915435997

2022-07-10 07:00 UTC, Endaris commented
I also gotta say that "I have integrated all your feedback" is a very lazy way to not answer questions or explain why you didn't apply suggestions and makes me feel like I wasted my time with my review of your other PR.

2022-07-10 20:56 UTC, Shosoul requested changes
I personally am struggling to understand a lot of this PR. I think too much was done at once here, and there are changes all over the place, so I struggle to understand how it works in general, what changed, and the justifications. This might need to get split up into separate PRs. I also thought that we would able to work on this during the cleanup together as a group, so we could all be on the same page. I do think that this PR (or a future and more tailored one) might need to be a little more user friendly. For instance, I don't think we should make it possible to scale the game to a size bigger than the monitor available.  

I also can understand the frustrations of Endaris. I think that we all kind of dropped the ball communication wise, but I do think that we should try to keep PRs tailored for more specific things, and let the person acknowledge a reason for closing a pr first.

2022-07-16 23:24 UTC, JamesVanBoxtel commented on game.lua
> +  panels_init()
Localization needs to be reloaded to get the new font. I'll make sure character and stage get loaded in the standard order and comment better.

2022-07-16 23:24 UTC, JamesVanBoxtel commented on conf.lua
> +require("globals")
Fixed in the other PR

2022-07-16 23:26 UTC, JamesVanBoxtel commented on conf.lua
> +  readConfigFile(config)
Fixed in the other PR

2022-07-16 23:40 UTC, JamesVanBoxtel commented
@Endaris WRT the assets reloading each option change, I have made it so it only reloads if the scale actually changes. I think we still want the reload though so the user can immediately see the new scale / resolution and see if they like the way it looks.

For the confusing options:
The idea of "auto" is that it uses the biggest scale that will fit on your monitor "snapping" to the right one. So if your monitor only fits 1.2 scale, it will use 1. This should probably be the default because it looks the best.

Could we name it something else that would make sense? or do we need to maybe add an explanation text part of options that can explain it better?

As for the fixed scales, the idea behind those is if you want to run at a bigger window size, but not use the biggest scale. For example you want to run full screen, your screen supports 1.5, but you want to use 1. Maybe that feature is too niche and we should just remove it for now.

I have also brought back the other PR and based this one off that, so it should be quite a bit smaller.

2022-07-16 23:42 UTC, JamesVanBoxtel commented
We will need to wait till it lands to finish reviewing this since its based off that branch.

2022-07-24 17:13 UTC, Shosoul requested changes
Looks really good! Did find a couple bugs though.

The initial resolution stays the same until you restart the game, so I got confused by that at the beginning since it only scaled the game when I changed options.

There's some weird shenanigans with the game it resizing to adjust for when I go out of full-screen, and it only shows part of the game. I'll have to test more to find out what's going on for that. Otherwise this is really cool!

2022-07-24 23:02 UTC, JamesVanBoxtel commented
Hmm I tried to reproduce the issues you described on windows and couldn't. Can you give steps and more details?

2022-07-24 23:24 UTC, Shosoul commented
For the first and second issue, it might have been that I hadn't gotten the most recent version of the PR. I'll keep testing. I did find a new bug, however, with easy reproduce. The game crashes if you are mid-game (like 1pvs yourself for example) and you try to move the window while in windowed mode with:
`main.lua:101: graphics.lua:291: attempt to index a nil value`

2022-07-24 23:46 UTC, JamesVanBoxtel commented
Ahh yeah, I've seen that, probably cause its reloading the assets but they are in use. Maybe I can mark it to not reload assets till the match is over

2022-07-26 05:25 UTC, Endaris requested changes

2022-07-26 05:25 UTC, Endaris commented on options.lua
> +  local scaleOptions = {"auto", "scaled"}
I would probably call these "Fit To Window" and "Scale by" and then put the discrete values for scaling into a subselection (we don't have those? uh oh, just make it do nothing if Fit To Window is selected).
And then in the next menu point that is exclusive for the Scale by thing, that should have "Auto, 1, 1.5, ...". That way it is more transparent what the difference between the two types of scaling is (especially if you have a regular screen resolution where there appears to be no visible difference between the two). Assuming _I_ actually understood the difference correctly.

In the long term that change would also make it easy to later replace the discrete values with Sankyr's slide selector instead so that Android users can fit their scale proper to make the game as big as possible on their screens

2022-07-26 05:25 UTC, Endaris commented on graphics_util.lua
> +  local scaleSuffixString = "@" .. scale .. "x"
We need to update essentially all the graphics related readmes for modding to make this new thing known.

2022-07-26 05:34 UTC, Endaris commented on options.lua
> +  local scaleOptions = {"auto", "scaled"}
Actually one thing that confuses me is that using scale 1 doesn't make the game appear smaller but still scales it to the window size. From my understanding that should actually put the game in 1280x720 resolution with letterboxing, even if I'm using a maximized or fullscreen window.

2022-07-28 15:59 UTC, JamesVanBoxtel commented on game.lua
> +  Localization.init(localization)
We really only need to do this to create new fonts with love.graphics.newFont with the new DPI scale.

It looks like I could extract that part out of set_language into the theme and just call that to update the global font.

2022-07-28 15:59 UTC, JamesVanBoxtel commented on game.lua
> +  characters_init()
Unless we write code to draw stuff on screen to show the user we are loading that won't actually do much. Perhaps we could borrow the code that shows loading stuff at game startup.

I do agree that it might be nice to extract the graphics loading out of the inits and only call that, but we are really trading off complexity for modularity.

If you think that's important before landing this I can explore it.

2022-07-28 15:59 UTC, JamesVanBoxtel commented on game.lua
> +    menu:reloadGraphics()
The font actually does change because it needs to use the new DPI. Shosoul actually found a bug that made me write this because the menus would look blurry cause they didn't update to use the new font.

2022-07-28 15:59 UTC, JamesVanBoxtel commented on graphics_util.lua
> +  local scaleSuffixString = "@" .. scale .. "x"
Agreed. I'll see if I can put something in. We do need to think in the future how to make the readme's more accessible though, they are hard to fit on one page and can't easily be accessed out of the game right now. They should also support formatting. Maybe markdown or HTML

2022-07-28 15:59 UTC, JamesVanBoxtel commented on options.lua
> +  local scaleOptions = {"auto", "scaled"}
Huh that's weird, I can't reproduce this, can you send me a video on discord or something?

2022-07-28 15:59 UTC, JamesVanBoxtel commented on options.lua
> +  local scaleOptions = {"auto", "scaled"}
I think the "Fit to Window" is a good idea. Maybe we should have "Automatic" be its own type, and then the third one would be called "Fixed Scale"? and we would only show the second menu option in that case?

2022-07-29 00:28 UTC, Endaris commented on graphics_util.lua
> +  local supportedScales = {3, 2, 1}
By always going in this order, wouldn't that mean that if I'm on scale 1 and I have a @2x and a normal sized asset in my folder, that the game will always take the @2x asset and scale it down even though I already have a perfectly fine asset in the size I need?

2022-07-29 01:14 UTC, JamesVanBoxtel commented on graphics_util.lua
> +  local supportedScales = {3, 2, 1}
Yes that's correct. I haven't tested but theoretically the 1x assets will look better. We just don't have any themes / characters that do both yet. Should we track that as a separate issue or do you think its important here?

2022-07-29 01:23 UTC, Endaris commented on graphics_util.lua
> +  local supportedScales = {3, 2, 1}
I think the moment a modder creates @2x assets, including the 1x asset is very little work and I'd see it as par for the course. Considering how @2x is 1440p and small laptop monitors like mine apparently pretend against PA that they are only 1280x720 screens. All the more impactful if someone actually goes ahead and adds @3x assets.
I don't mind particularly if this would go into an issue first because I think that we want to enable the user to freely select the scale instead of using presets in the future anyway. Can address it together with that then.

2022-07-29 01:32 UTC, JamesVanBoxtel commented on graphics_util.lua
> +  local supportedScales = {3, 2, 1}
Agreed. We will need to do more testing with making sure it uses the right version for the different scales and looks good too. I'll write an issue now.

2022-07-30 02:49 UTC, Endaris commented on options.lua
> +  local scaleOptions = {"auto", "scaled"}
Yep, sounds good after clearing up yesterday what the "Automatic" type was!

2022-07-30 04:22 UTC, JamesVanBoxtel commented on graphics_util.lua
> +  local scaleSuffixString = "@" .. scale .. "x"
Done

2022-07-30 23:32 UTC, Shosoul approved these changes
This will probably be touched up a lot as we get community feedback, but good for now

2022-07-30 23:44 UTC, Shosoul requested changes
Unsure why fixed scale is now its own option in the menu now, it will confuse people seeing it blank and it doesnt need its own option

Menu also disappears when resizing the game for some reason... 

scale text is blurry 
![image](https://user-images.githubusercontent.com/18148657/182003672-5a7ed739-a20a-469a-8cd1-6159ca477d3d.png)

Could we try applying the graphic change after the player goes back so that their screen doesn't go nuts while trying to change it?

Should we make it impossible to scale to a size larger than the monitor?

2022-07-30 23:54 UTC, Endaris commented
> Should we make it impossible to scale to a size larger than the monitor?

By design, we shouldn't as it is a useful option for android users.

2022-07-31 00:10 UTC, Shosoul commented
> > Should we make it impossible to scale to a size larger than the monitor?
> 
> By design, we shouldn't as it is a useful option for android users.

We could just explicitly allow it for android users with `love.system.getOS() == "Android"` or something

2022-07-31 00:20 UTC, JamesVanBoxtel commented
> Menu also disappears when resizing the game for some reason...
Can you send me a video of this?

> Could we try applying the graphic change after the player goes back so that their screen doesn't go nuts while trying to change it?
The reason I think its important to update immediately is so you can see how the scale looks and pick a new setting if you don't like it. What do you mean by the screen going nuts?

2022-07-31 21:39 UTC, JamesVanBoxtel commented
@Shosoul is this ready to land?

2022-07-31 23:10 UTC, Shosoul approved these changes

2022-08-01 00:15 UTC, merged