Added input system that doesn't depend on variable step
panel-attack/panel-attack pull request #576
Opened 2022-07-17 19:02 UTC by Sankyr

this is the first of many PRs to attempt to integrate the changes in:
https://github.com/Sankyr/panel-attack/tree/custom-run

2022-07-18 04:02 UTC, JamesVanBoxtel reviewed
Lots of review feedback I know, but this is an important part of the system so should be done well.

2022-07-18 04:02 UTC, JamesVanBoxtel commented on input2.lua
> +function input2:getJoystickButtonName(joystick, button)
I'm not sure there is a clear reason why we have reimplemented the mapping of joystick GUIDs? Why not reuse Input.getJoystickGUID from the original input? Maybe this is something different and needs a better name?

2022-07-18 04:02 UTC, JamesVanBoxtel commented on main.lua
> +function love.gamepadpressed(joystick, button)
I thought we were just treating gamepads as "joysticks" what does this buy us and how do we stop from getting duplicate presses?

2022-07-18 04:02 UTC, JamesVanBoxtel commented on tableUtils.lua
> +local tableUtils = {}
Is this the same table util code just moved or something else going on here?

2022-07-18 04:12 UTC, Sankyr commented on consts.lua
> +local tableUtils = require("tableUtils")
It's literally the same code I just changed the name to tableUtils and wrapped it in a table so it's:
1) not writing to the default table methods
2) able to be required locally

I could go through all usage of the existing one and switch them to this one so I can delete the other one?

2022-07-18 04:15 UTC, Sankyr commented on input.lua
> +local input2 = require("input2")
sure but should it be capitalize it since it's not a class, just a collection of functions?

2022-07-18 05:02 UTC, Sankyr commented on input2.lua
> +local stickMap = {
Done.

2022-07-18 05:06 UTC, Sankyr commented on input2.lua
> +      local quantizedDir = math.floor(((dir + 180 + 45 / 2) / 45.0) % 8) + 1
Done.

2022-07-18 05:09 UTC, Sankyr commented on input2.lua
> +      local mag = math.sqrt(joystick:getGamepadAxis(x) * joystick:getGamepadAxis(x) + joystick:getGamepadAxis(y) * joystick:getGamepadAxis(y))
Done.

2022-07-18 05:14 UTC, Sankyr commented on input2.lua
> +    if self.raw.isDown[key] == 1 then
Updated the header comment to address this

2022-07-18 05:16 UTC, Sankyr commented on tableUtils.lua
> +local tableUtils = {}
yes, it's the same code just moved, I explained why in a previous comment

2022-07-18 05:18 UTC, Sankyr commented on main.lua
> +function love.gamepadpressed(joystick, button)
in the love.keypress function there is a scancode variable, controller inputs don't have scancodes and I'm filtering those out so they only get read from here.
What this gets us is access to the joystick object along with the keypress event which can be used to identify the joystick that triggered the event.

2022-07-18 05:21 UTC, Sankyr commented on input2.lua
> +function input2:getJoystickButtonName(joystick, button)
the only real reason for this function is to guarantee that the joystick ID remains consistent between sessions. 
I couldn't tell based on the documentation if the joystick ID always started at 1 or not (they say it's consistent for the life time of the game, but not what value it starts with).
Essentially I wanted to avoid the case where a joystick comes in with ID 1, but then the next time it's plugged in it has ID 3 and the input config only pairs with joystick of ID 1.

2022-07-18 05:24 UTC, Sankyr commented on input2.lua
> +      self.player[i].isPressed[key] = self.raw.isPressed[GAME.input.inputConfigurations[i][key]]
Done.
I will need to setup a way to actually test this since I still don't have a functioning 2player system in my main branch yet

2022-07-18 05:34 UTC, Sankyr commented on input2.lua
> +      self.player[i].isPressed[key] = self.raw.isPressed[GAME.input.inputConfigurations[i][key]]
I also don't have 2 controllers of the same type to test with

2022-07-18 06:05 UTC, Shosoul commented on input2.lua
> +      self.player[i].isPressed[key] = self.raw.isPressed[GAME.input.inputConfigurations[i][key]]
Keyboard might be good. People might even share a keyboard for 2p local sometimes

2022-07-18 06:06 UTC, Shosoul commented on input2.lua
> +function input2:getJoystickButtonName(joystick, button)
The GUID is consistent and does not ever change

2022-07-18 06:14 UTC, Shosoul commented on main.lua
> +function love.gamepadpressed(joystick, button)
I thought love.joystickpressed returned the joystick in addition to the pressed button

2022-07-18 06:20 UTC, Shosoul commented on main.lua
> +function love.gamepadpressed(joystick, button)
love.keypressed also returns the key that was pressed in addition to the scancode, so just use the key

2022-07-18 06:29 UTC, Shosoul commented on input2.lua
> +      local quantizedDir = math.floor(((dir + 180 + 45 / 2) / 45.0) % 8) + 1
Would it be possible to explain this further? Such as how it works more specifically, what each number does, why it's there, and why that specific value. Maybe put every number in that equation as a local variable for easier documentation and stuff

2022-07-18 06:43 UTC, Sankyr commented on input2.lua
> +function input2:getJoystickButtonName(joystick, button)
Ya, I was talking about the JoystickID, controllers of the same type have the same GUID, the JoystickID separates them

2022-07-18 06:45 UTC, Sankyr commented on main.lua
> +function love.gamepadpressed(joystick, button)
first comment:
yes, that's why I used it

second comment:
I answered that in my previous comment

2022-07-18 06:45 UTC, Sankyr commented on input2.lua
> +      self.player[i].isPressed[key] = self.raw.isPressed[GAME.input.inputConfigurations[i][key]]
I can test that, I just need a scenario to actually test with until I get multiplayer working in my main branch

2022-07-18 07:18 UTC, Sankyr commented on input2.lua
> +      local quantizedDir = math.floor(((dir + 180 + 45 / 2) / 45.0) % 8) + 1
Done.

2022-07-18 07:20 UTC, Shosoul commented on main.lua
> +function love.gamepadpressed(joystick, button)
Guess I'm confused here. I don't know how the scancode is relevant, or why we used gamepad instead of joystick.

2022-07-18 07:27 UTC, Shosoul commented on main.lua
> +function love.gamepadpressed(joystick, button)
Maybe it's better I look at this part when I have access to a computer instead of on my phone

2022-07-18 07:28 UTC, Shosoul commented on input2.lua
> +function input2:getJoystickButtonName(joystick, button)
Why not just save the actual joystick itself?

2022-07-18 07:56 UTC, Shosoul commented on main.lua
> +function love.gamepadpressed(joystick, button)
Could you just use `key` instead of the scancode?

2022-07-18 20:31 UTC, Shosoul commented on main.lua
> +function love.gamepadpressed(joystick, button)
So if I'm understanding this right, both keyboard and joystick inputs go through this method?

2022-07-19 15:52 UTC, JamesVanBoxtel commented on input2.lua
> +function input2:getJoystickButtonName(joystick, button)
Yes that's exactly what Input.getJoystickGUID does. the first one gets no suffix, the next gets #2 added on to the end

2022-07-19 15:56 UTC, JamesVanBoxtel commented on main.lua
> +function love.gamepadpressed(joystick, button)
From what I read online we still need to support "joystick" for some weird controllers, so it seems like maybe we should just only use that one for now? Seems fine to filter out from keypress though so you get the joystick like this.

2022-07-20 00:14 UTC, Endaris commented
I'm looking at the PR now and I have some questions.
1. The PR is to beta. Do we actually want to pull this into beta or do we want this in our not-yet-existing experimental branch for cleanup?
2. Is it part of the plan that we adapt Sankyr's idea of having a parallel implementation instead of straight up replacing the old one? Cause from what I can tell the branch has 2 implementations for input.

2022-07-20 04:32 UTC, JamesVanBoxtel commented on input.lua
> +local input2 = require("input2")
Probably? I mean the only distinction is if you can instantiate one... probably not big enough of a distinction to have a different naming style?

2022-07-20 04:34 UTC, JamesVanBoxtel commented
I think since this is a parallel implementation and has dead code it probably should go to a feature branch. I can make one.

2022-07-20 04:46 UTC, Sankyr commented on consts.lua
> +local tableUtils = require("tableUtils")
in that case can we structure it like they did, by returning a local table so we can import it with the local var = require('') style?

2022-07-20 05:39 UTC, Sankyr commented on main.lua
> +function love.gamepadpressed(joystick, button)
when you say support joystick, you just mean use the love.joystickpressed function instead of the love.gamepadpressed ?

2022-07-20 05:43 UTC, Endaris commented
Okay, cause I was actually getting confused by this since my first instinct on the inputManager thing was to call it input instead but the old implementation was still there so it was not an option. @Sankyr Am I going right in the assumption that aside from the hooks provided by love, such as keypressed, no other part from input.lua is used anymore?

2022-07-20 07:11 UTC, Sankyr commented on input2.lua
> +function input2:getJoystickButtonName(joystick, button)
ah, I see. I didn't realize that's what that did my bad...
However I prefer my implementation since it doesn't require iterating over all joysticks each time (at the cost of some space per joystick)

2022-07-20 07:23 UTC, Shosoul commented on input2.lua
> +function input2:getJoystickButtonName(joystick, button)
However, some devices that would get recognized as joysticks do not get recognized as gamepads.

2022-07-20 08:18 UTC, Sankyr commented on input2.lua
> +function input2:getJoystickButtonName(joystick, button)
Did you mean to add this comment to the thread below?
("I thought we were just treating gamepads as "joysticks" what does this buy us and how do we stop from getting duplicate presses?")

2022-07-20 08:20 UTC, Shosoul commented on input2.lua
> +function input2:getJoystickButtonName(joystick, button)
Yea. I'll say it again over there

2022-07-20 08:22 UTC, Shosoul commented
I should note that I've only kept my comments to what others have discussed, when I get home on Saturday I may have entirely new questions, comments, and other stuff since I won't be looking at a phone screen only using the GitHub app lol

2022-07-20 09:27 UTC, Sankyr commented on input.lua
> +local input2 = require("input2")
so are you willing to make all modules capitalized (and in turn all file names except main.lua)?

2022-07-20 19:32 UTC, Endaris requested changes
Mostly have various suggestions regarding structure and readability. The system for tracking inputs itself looks functional enough. I didn't check joystick functionality in detail, just kind of assuming this works.

One thing we should start to consider as part of this PR is what kind of unit tests we can write for this dead code to make present problems immediately visible now and also later when we integrate Sankyr's development branch.

2022-07-20 19:32 UTC, Endaris commented on inputManager.lua
> +  joystickSensitivity = .5,
Assuming the situation where two players are playing 2p vs local with gamepads+stick, I think it would be fair to assume that joystick sensitivity should be possible to be set per player and thus be part of the input configuration instead of a universally applied setting.

2022-07-20 19:32 UTC, Endaris commented on inputManager.lua
> +  player = {},
Instead of putting the information into the comments, how about creating a more readable naming scheme for these three groups?
Along the lines of
```Lua
mappedKeys = {}
allKeys = {}
player = {}
```
and each player could then have their own mappedKeys table and then you can just go ahead and write things like `if player[1].mappedKeys["A"].isUp == KEY_STATE_ACTION.APPLY`, `mappedKeys["5"].isPressed = KEY_STATE_ACTION.DISCARD` etc. (or nil, 1, 2 if you don't like my other suggestion).
Or any other names that more accurately suggest what is saved in these tables.

2022-07-20 19:32 UTC, Endaris commented on inputManager.lua
> +      for _, button in ipairs(stickMap[quantizedDir]) do
I feel like most of this could instead be in its own extension method to `Joystick` instead of being plugged in here. As Joystick handling is kind of its own beast in contrast to tracking the **effective** inputs that are applied I think it would be generally a good idea to move all of that (including `stickMap` etc.) into its own file (JoystickExtensions or something) and only keep a mapping method in `input` that is reduced to something like
```Lua
for _, joystick in ipairs(love.joystick.getJoysticks()) do 
  for buttonName, magSquared in joystick:getInputStates() do
  -- set self.raw / self.allKeys
  end
end
```
Not sure if that would work since I didn't take the time to understand the joystick logic in detail but I feel like it would.

2022-07-20 19:32 UTC, Endaris commented on inputManager.lua
> +  end
Extract this into a method like `updateKeyStates`?

2022-07-20 19:32 UTC, Endaris commented on inputManager.lua
> +  end
Extract this into two methods like `getMappedKeyStates` and `getPlayerKeyStates`?
Think it'd be good to be less verbose in such core function such as `update`

2022-07-20 22:11 UTC, Shosoul commented on inputManager.lua
> +--     there needs to be a marker value which update can track to see if the state has already lasted for a full frame or not
Why just not save the actual button class and use the native methods from there?

2022-07-21 01:57 UTC, Sankyr commented
> Mostly have various suggestions regarding structure and readability. The system for tracking inputs itself looks functional enough. I didn't check joystick functionality in detail, just kind of assuming this works.
> 
> One thing we should start to consider as part of this PR is what kind of unit tests we can write for this dead code to make present problems immediately visible now and also later when we integrate Sankyr's development branch.

testing inputManager.lua would be tricky, mainly because:
1) it's all about managing live input, this can be somewhat simulated since it doesn't overwrite the LOVE methods directly
2) it is dependent on the state of the input config, I could make this a parameter so a test config could be used
3) the method of testing, we could make a test module and run it under game like the other test function that require LOVE, but it would be hard to control input in that state, an alternative would be to make a sub folder with a custom main, with a custom run that would only run 1 frame of update and within that frame we can simulate multiple frames of input for testing

Thoughts?

2022-07-21 01:59 UTC, Sankyr commented on inputManager.lua
> +--     there needs to be a marker value which update can track to see if the state has already lasted for a full frame or not
I really like that, I'll probably change the names though.
Shosoul, what do you mean by "button class"?

2022-07-21 02:50 UTC, Sankyr commented on main.lua
> +function love.gamepadpressed(joystick, button)
Switched to love.joystickpressed

2022-07-21 02:51 UTC, Sankyr commented on inputManager.lua
> +--     there needs to be a marker value which update can track to see if the state has already lasted for a full frame or not
Added KEY_STAGE_STATE

2022-07-21 03:00 UTC, Sankyr commented on inputManager.lua
> +  joystickSensitivity = .5,
nice catch, however this would be pretty annoying to implement, mind if I just put a TODO on this for now?

2022-07-21 03:06 UTC, Sankyr commented on inputManager.lua
> +  player = {},
I'll change raw to allKeys, but I would prefer not to add a nesting to the top level configured input since that is the one used most often throughout the game.
It would basically mean changing inputManager.isDown["Swap1"] to inputManager.mappedKeys.isDown["Swap1"] for all basic buttons
let me know if that's a fair compromise?

2022-07-21 04:58 UTC, Sankyr commented on inputManager.lua
> +  end
Done.

2022-07-21 05:03 UTC, Sankyr commented on inputManager.lua
> +  end
Moved to 1 function, updateKeyMaps.

2022-07-21 05:49 UTC, Endaris commented on inputManager.lua
> +  joystickSensitivity = .5,
TODO is fine for me, as this is a feature independent from the UI rework.

2022-07-21 05:51 UTC, JamesVanBoxtel commented
While I do think testing end to end could be quite complicated, you could at least test some of the key functions. Things like the stick map and quantizing, and other important tricky functions

2022-07-21 05:54 UTC, Sankyr commented on inputManager.lua
> +  joystickSensitivity = .5,
Done.

2022-07-21 05:56 UTC, Sankyr commented on consts.lua
> +local consts = {
can I add a TODO, and do this in a future PR?

2022-07-21 05:57 UTC, Endaris commented on inputManager.lua
> +  player = {},
To clarify, since this isn't visible in the current PR: The top level tables are going to be used for menuing outside of the select screen and nothing else? Otherwise this proposal doesn't make a lot of sense to me.

2022-07-21 06:07 UTC, Endaris commented on input.lua
> +local input2 = require("input2")
I think once the old input is gone, this should definitely be called Inputs or inputs (no big preference there), not inputManager as it has better readability, manager really is just a filler word at that point.
Think of `inputs:update()`, `inputs.isDown["Raise"]`.

2022-07-21 06:09 UTC, Sankyr commented on input.lua
> +local input2 = require("input2")
I agree with you there

2022-07-21 06:21 UTC, Endaris commented on inputManager.lua
> +--     there needs to be a marker value which update can track to see if the state has already lasted for a full frame or not
Gotta say I'm not too happy with the names, mainly because they are of different linguistic categories.
EVENT_HANDLER is a thing, UPDATE is a process or a verb. Ideally the progress through the different stages is also visible in the chosen names for the values and that's not going to happen if the words have no visible connection with each other.
From what I understand, `1` is for initial tracking of a new key state without using it to do anything. `2` means you're keeping the value to actually process and then discard it (in the next update, that's why I originally suggested DISCARD). So instead maybe DETECTED and APPLIED or APPLYING. And for the table itself maybe KEY_CHANGE?
Then you have KEY_CHANGE.NONE, KEY_CHANGE.DETECTED and KEY_CHANGE.APPLYING which reads like 10 times better in my eyes.

2022-07-21 06:50 UTC, Sankyr commented on inputManager.lua
> +--     there needs to be a marker value which update can track to see if the state has already lasted for a full frame or not
naming things is hard, but this suggestion is much better than mine, I'll take it :)

2022-07-21 07:10 UTC, Endaris commented on inputManager.lua
> +      for _, button in ipairs(stickMap[quantizedDir]) do
I think you can go a step further here.
In my opinion stickMap, antiStickmap shouldn't even show up in inputs because they're super specific to joysticks. From the perspective of inputs, all you really need to know about joysticks is:
There are 4 buttons. They are being pressed on that frame or not. 
The joystickManager (I'd still prefer calling it extensions, even if you don't directly extend the class) needs to return only that information and has to expose nothing about quantizedDirs or the fact that only 2 buttons can be pressed at the same time and only in specific constellations.

2022-07-21 07:22 UTC, Endaris commented on inputManager.lua
> +  for key, value in pairs(self.allKeys.isUp) do
You could immediately discard the values returned by pairs using the underscore as you are not using them.

2022-07-21 07:32 UTC, Sankyr commented on inputManager.lua
> +  for key, value in pairs(self.allKeys.isUp) do
Done.

2022-07-22 05:32 UTC, JamesVanBoxtel approved these changes
Couple minor things and then I think this is ready from my end

2022-07-22 05:32 UTC, JamesVanBoxtel commented on consts.lua
> +local consts = {
That's fine, but we should do this before landing the feature branch so we don't have duplicate costs

2022-07-22 05:32 UTC, JamesVanBoxtel commented on inputManager.lua
> +--     there needs to be a marker value which update can track to see if the state has already lasted for a full frame or not
New names seem good, lets update the comment above to refer to them.

2022-07-22 08:59 UTC, Sankyr commented on inputManager.lua
> +      for _, button in ipairs(stickMap[quantizedDir]) do
ah, that's a better solution, managed to eliminate the anti-stick map too (what was I thinking with that...)

2022-07-22 09:01 UTC, Sankyr commented on consts.lua
> +local consts = {
Will do

2022-07-22 09:08 UTC, Sankyr commented on inputManager.lua
> +--     there needs to be a marker value which update can track to see if the state has already lasted for a full frame or not
Done.

2022-07-22 09:11 UTC, Sankyr commented on inputManager.lua
> +  player = {},
the top level inputs would be used for everything except for local play

2022-07-22 09:37 UTC, Sankyr commented on consts.lua
> +local tableUtils = require("tableUtils")
updated everything to tableUtils

2022-07-24 21:56 UTC, Shosoul commented on consts.lua
> +  KEY_NAMES = {"Up", "Down", "Left", "Right", "Swap1", "Swap2", "TauntUp", "TauntDown", "Raise1", "Raise2", "Start"},
Lowercase these, as it can cause confusion with prior key files 
![image](https://user-images.githubusercontent.com/18148657/180659278-a23d364a-f654-4696-95a0-b3fd3aac8c4b.png)

2022-07-24 21:56 UTC, Shosoul commented on main.lua
> +function love.joystickpressed(joystick, button)
Would it make more sense to move these methods to `inputManager.lua` or `joystickManager.lua`?

2022-07-24 21:56 UTC, Shosoul commented on joystickManager.lua
> +  stickMap = {
Is there a reason we use 8 instead of 4?

2022-07-24 22:39 UTC, JamesVanBoxtel commented on main.lua
> +function love.joystickpressed(joystick, button)
I personally think we should have all the love handlers in one call back, probably in main.lua

2022-07-25 00:21 UTC, Sankyr commented on consts.lua
> +  KEY_NAMES = {"Up", "Down", "Left", "Right", "Swap1", "Swap2", "TauntUp", "TauntDown", "Raise1", "Raise2", "Start"},
I capitalized them to prevent confusion with the raw key codes (up, down, left, right mainly). However since they are stored in separate tables now it doesn't really matter

2022-07-25 00:22 UTC, Sankyr commented on main.lua
> +function love.joystickpressed(joystick, button)
I agree with jambox on this

2022-07-25 00:23 UTC, Sankyr commented on joystickManager.lua
> +  stickMap = {
To handle diagonal inputs

2022-07-25 00:23 UTC, Shosoul commented on consts.lua
> +  KEY_NAMES = {"Up", "Down", "Left", "Right", "Swap1", "Swap2", "TauntUp", "TauntDown", "Raise1", "Raise2", "Start"},
It mixes it together with the previous tables though

2022-07-25 00:24 UTC, Shosoul commented on joystickManager.lua
> +  stickMap = {
diagonal inputs dont exist in PA, so I was wondering if we could simplify it because of that

2022-07-25 00:24 UTC, Sankyr commented on consts.lua
> +  KEY_NAMES = {"Up", "Down", "Left", "Right", "Swap1", "Swap2", "TauntUp", "TauntDown", "Raise1", "Raise2", "Start"},
"it doesn't really matter" as in I'll change it to lowercase when I get back

2022-07-25 00:27 UTC, Shosoul commented on consts.lua
> +  KEY_NAMES = {"Up", "Down", "Left", "Right", "Swap1", "Swap2", "TauntUp", "TauntDown", "Raise1", "Raise2", "Start"},
sounds good
```suggestion
  KEY_NAMES = {"up", "down", "left", "right", "swap1", "swap2", "taunt_up", "taunt_down", "raise1", "raise2", "start"},
```

2022-07-25 00:51 UTC, Sankyr commented on consts.lua
> +  KEY_NAMES = {"Up", "Down", "Left", "Right", "Swap1", "Swap2", "TauntUp", "TauntDown", "Raise1", "Raise2", "Start"},
Why underscores in the key names, aren't we trying to do camelCase?

2022-07-25 00:51 UTC, Shosoul commented on main.lua
> +function love.joystickpressed(joystick, button)
sounds good to me

2022-07-25 00:51 UTC, Sankyr commented on consts.lua
> +  KEY_NAMES = {"Up", "Down", "Left", "Right", "Swap1", "Swap2", "TauntUp", "TauntDown", "Raise1", "Raise2", "Start"},
Also why tauntUp/Down instead of taunt1/2?

2022-07-25 00:52 UTC, Shosoul commented on consts.lua
> +  KEY_NAMES = {"Up", "Down", "Left", "Right", "Swap1", "Swap2", "TauntUp", "TauntDown", "Raise1", "Raise2", "Start"},
since that's what's saved in the file before, it wont mix up other files. Another solution I suppose would be to have the game  `nil` out the old ones so that they aren't there anymore

2022-07-25 01:02 UTC, Sankyr commented on joystickManager.lua
> +  stickMap = {
Can we add a TODO to revisit this question after PR3?
In my main branch the game responds to diagonal inputs the same way it does now (thanks to the network.lua input interface)
It's only in menus where you could use it

2022-07-25 01:05 UTC, Shosoul commented on joystickManager.lua
> +  stickMap = {
Hmm that's true, I forgot about that. We should keep the diagonals then

2022-07-28 14:48 UTC, Endaris commented
Suggestion based on peeking into the full branch at #583:
Let's make the new input manage all input instead of just keyboard and gamepad inputs.

Add
```Lua
-- Key groups: 
--   allKeys: every key read in by LOVE (includes keyboard, controller, and joystick) 
--   base (top level): all keys mapped by the input.configuration aliased to the consts.KEY_NAMES 
--   mouse: all mouse buttons, the position of the mouse and start/end coordinates for drag actions
--   player: list of individual input.configuration mappings also aliased by consts.KEY_NAMES 
local inputManager = { 
  isDown = {}, 
  isPressed = {}, 
  isUp = {}, 
  allKeys = { 
    isDown = {}, 
    isPressed = {}, 
    isUp = {}
  }, 
  mouse = {
    isDown = {}, 
    isPressed = {}, 
    isUp = {},
    clicks = {},
    x, y
  },
  --...
}

function inputManager:updateKeyStates(dt, keys)
  currentDt = dt 
  for key, _ in pairs(keys.isDown) do 
    if keys.isDown[key] == KEY_CHANGE.DETECTED then
      keys.isDown[key] = KEY_CHANGE.APPLIED
    else 
      keys.isDown[key] = KEY_CHANGE.NONE
      keys.isPressed[key] = dt
    end 
  end 
 
  for key, _ in pairs(keys.isPressed) do 
    keys.isPressed[key] = keys.isPressed[key] + dt 
  end 
   
  for key, _ in pairs(keys.isUp) do 
    if keys.isUp[key] == KEY_CHANGE.DETECTED then 
      keys.isUp[key] = KEY_CHANGE.APPLIED   
    else 
      keys.isUp[key] = KEY_CHANGE.NONE 
    end 
  end 
end

function inputManager:update(dt) 
  self:joystickToButtons() 
  self:updateKeyStates(dt, self.allKeys)
  self:updateKeyStates(dt, self.mouse)
  self:updateKeyMaps()
end 

function inputManager:mousePressed(x, y, button)
  self.mouse.isDown[button] = KEY_CHANGE.DETECTED
  self.mouse.clicks[button].moveStart = {x = x, y = y}
end

function inputManager:mouseReleased(x, y, button)
  self.mouse.isDown[button] = KEY_CHANGE.NONE
  self.mouse.isPressed[button] = KEY_CHANGE.NONE
  self.mouse.isUp[button] = KEY_CHANGE.DETECTED
  self.mouse.clicks[button].moveEnd = {x = x, y = y}
end

function inputManager:mouseMoved(x, y)
  self.mouse.x = x
  self.mouse.y = y
end
```

and in main.lua
```Lua
-- Handle a mouse or touch press
function love.mousepressed(x, y, button)
  inputManager:mousePressed(x, y, button)
  for menu_name, menu in pairs(CLICK_MENUS) do
    menu:click_or_tap(transform_coordinates(x, y))
  end
end

function love.mousereleased(x, y, button)
  inputManager:mouseReleased(x, y, button)
end

function love.mousemoved(x, y)
  inputManager:mouseMoved(x, y)
end
```

That way we can avoid having 2 different input processes for mouse and keyboard. And semantically it only makes sense to also store mouse inputs in `inputs`.

2022-07-31 00:01 UTC, Sankyr commented on consts.lua
> +  KEY_NAMES = {"Up", "Down", "Left", "Right", "Swap1", "Swap2", "TauntUp", "TauntDown", "Raise1", "Raise2", "Start"},
> Suggestion based on peeking into the full branch at #583: Let's make the new input manage all input instead of just keyboard and gamepad inputs.

why add  self.mouse.clicks[button]? can we just store the position in (x, y) like you do in the mouseMove function?

2022-07-31 00:01 UTC, Sankyr commented
> Suggestion based on peeking into the full branch at https://github.com/panel-attack/panel-attack/pull/583: Let's make the new input manage all input instead of just keyboard and gamepad inputs.

why add self.mouse.clicks[button]? can we just store the position in (x, y) like you do in the mouseMove function?

2022-07-31 01:46 UTC, Sankyr commented on consts.lua
> +  KEY_NAMES = {"Up", "Down", "Left", "Right", "Swap1", "Swap2", "TauntUp", "TauntDown", "Raise1", "Raise2", "Start"},
actually wait, why is this an issue again, the inputs work even with the old names in the file?

2022-07-31 01:49 UTC, Shosoul commented on consts.lua
> +  KEY_NAMES = {"Up", "Down", "Left", "Right", "Swap1", "Swap2", "TauntUp", "TauntDown", "Raise1", "Raise2", "Start"},
because it's confusing seeing both

2022-07-31 01:50 UTC, Endaris commented
> > Suggestion based on peeking into the full branch at #583: Let's make the new input manage all input instead of just keyboard and gamepad inputs.
> 
> why add self.mouse.clicks[button]? can we just store the position in (x, y) like you do in the mouseMove function?

Not sure if that's the smartest way but the idea was that you could detect different drags for different buttons.
Totally unlikely scenario:
You click Mouse 1, start dragging, click mouse 2, keep dragging, let lose of mouse 1, etc. so you can track these independently. Probably makes no sense but if we wanted to be max flexible there we would do it.

2022-07-31 02:06 UTC, Sankyr commented
Ya, that makes sense, but currently the only process that uses "drag" is the slider atm, and that's not even a true drag, it just polls the current position of the mouse while clicked.
I vote we don't add it until we have a use case for it (it's a simple change anyway)

2022-07-31 02:09 UTC, Endaris commented
> Ya, that makes sense, but currently the only process that uses "drag" is the slider atm, and that's not even a true drag, it just polls the current position of the mouse while clicked. I vote we don't add it until we have a use case for it (it's a simple change anyway)

Yeah, fair

2022-07-31 04:54 UTC, JamesVanBoxtel commented on consts.lua
> +  KEY_NAMES = {"Up", "Down", "Left", "Right", "Swap1", "Swap2", "TauntUp", "TauntDown", "Raise1", "Raise2", "Start"},
I don't really mind either way. The important thing is in later PRs I'd like to avoid the player having to reconfigure inputs yet again.

2022-07-31 04:57 UTC, JamesVanBoxtel approved these changes

2022-07-31 06:46 UTC, Sankyr commented on consts.lua
> +  KEY_NAMES = {"Up", "Down", "Left", "Right", "Swap1", "Swap2", "TauntUp", "TauntDown", "Raise1", "Raise2", "Start"},
I vote we revisit this in PR3 when these actually get used

2022-07-31 06:59 UTC, Endaris commented on consts.lua
> +  KEY_NAMES = {"Up", "Down", "Left", "Right", "Swap1", "Swap2", "TauntUp", "TauntDown", "Raise1", "Raise2", "Start"},
> I capitalized them to prevent confusion with the raw key codes (up, down, left, right mainly). However since they are stored in separate tables now it doesn't really matter

If this is the goal, I suggest you just stuff these into a pseudo enum. `KEY_NAMES = { UP = "up" ...` might look silly but if the distinction can be made clear that way, that's a super valid approach and also prevents problems from typos.

I hope I understand the point of discussion correctly here. I don't think there is a specific reason to postpone a decision on this matter. In my opinion it should keep matching the current keyV2.txt format, aka lower key.

2022-07-31 15:22 UTC, Sankyr commented
not sure what happened to the keycode thread, but I applied shosoul's change

2022-07-31 23:11 UTC, Shosoul approved these changes

2022-08-01 02:58 UTC, merged