Login Improvements
panel-attack/panel-attack pull request #950
Opened 2023-07-24 01:48 UTC by JamesVanBoxtel

Make login required
Remove socket setup code in update, it was already done on creation 
Create server object in the launcher instead of in the require
Random seed picked for the server if one not set
Consolidate denyLogin into one
Made methods smaller
Used the colon syntax for method definitions
Fixed some bugs in database selecting when the result is empty 
Fixed connections to close properly when the socket closes 
Fixed potential bug when login takes more than 2 seconds

2023-07-24 02:42 UTC, Shosoul requested changes

2023-07-24 02:42 UTC, Shosoul commented on server/PADatabase.lua
> +  for row in selectPlayerRecordCount:rows() do
What's the reason for changing it to this?

2023-07-24 02:42 UTC, Shosoul commented on server/PADatabase.lua
> +  for row in selectPlayerStatement:nrows() do
Why change this to using `for` instead of just having the database search it out?

2023-07-24 02:42 UTC, Shosoul commented on server/server_file_io.lua
> +        print("csprng_seed.txt could not be read.  Writing a new csprng_seed.txt")
Recommend including the csprng_seed in the message here., also convert to log

2023-07-24 02:42 UTC, Shosoul commented on server/Connection.lua
> +    return
I would leave in the warn messages, just in case, along with connection info

2023-07-24 02:42 UTC, Shosoul commented on server/Connection.lua
> +  if self.room == nil then
I would leave in the warn messages, just in case, along with connection info

2023-07-24 02:57 UTC, Shosoul commented
Whenever I try to log into the main server with this, the lobby is shown as empty with the "logging in..." message

2023-07-24 03:01 UTC, Shosoul commented
> Whenever I try to log into the main server with this, the lobby is shown as empty with the "logging in..." message

This happens when I try to change my username

2023-07-24 03:05 UTC, Shosoul commented
![screenshot_v047-2023-07-24-03-02-20](https://github.com/panel-attack/panel-attack/assets/18148657/d0d13fc8-713f-4198-8c52-61bd614b2dc4)
When I enter a match with someone, it uses the local 2p select screen instead of online I think

2023-07-24 04:54 UTC, Shosoul commented on server/Connection.lua
> +    return
I've seen it a decent amount actually

2023-07-24 04:54 UTC, Shosoul commented on server/PADatabase.lua
> +  for row in selectPlayerRecordCount:rows() do
Crashing, or just sending an error?

2023-07-25 04:02 UTC, Shosoul commented on server/PADatabase.lua
> +  for row in selectPlayerRecordCount:rows() do
I think it's faster for the database to search by itself instead of it going through lua

2023-12-14 01:27 UTC, Endaris commented on server/Connection.lua
> +      logger.warn("Login failure: Player (" .. user_id .. ") tried to use already taken name: " .. self.name)
The name check needs to happen in `handleUsername` already and
Otherwise a logged in user of the same name can be easily disconnected through a login attempt with their name when `self.server.nameToConnectionIndex[self.name] = self.index` is called at the end of `handleUsername`.

2023-12-14 01:36 UTC, Endaris commented on mainloop.lua
> -        return main_dumb_transition, {main_select_mode, "Error: " .. msg.choose_another_name.reason, 60, 300}
This is a "breaking" change in the sense that new client with old server will never pop the `choose_another_name` and get logged into a seemingly empty server message makes this a "breaking" change in a way:
When trying to login with a taken name, you get a couple seconds of "Logging in" and then this:
![grafik](https://github.com/panel-attack/panel-attack/assets/22120694/d2eea09f-c221-4f3a-bd9e-544f2cb47b25)
aka most certainly not logged in, just never realised because the message type was deprecated.
If server is updated first, this is not necessarily a problem as old client understands `deny_login` but unless we force beta and stable to get this at the same time (bad idea), we'll also need to test the old client + new server interaction *and* carefully plan the update path between server, stable and beta.
Imo it should be considered to give up on this rather inconsequential consolidation for now and put it in a separate branch so we can coordinate a merge together with eventual other upcoming changes to the network protocol.

2023-12-14 02:10 UTC, Endaris commented on server/server_file_io.lua
> -    logger.error("Failed to read leaderboard file with error: " .. error)
Granted, this probably never happens but if it does, having a log message would surely be nice to immediately know where to look?

2023-12-14 02:25 UTC, Endaris commented on serverLauncher.lua
> +local database = require("server.PADatabase")
can remove the require from `server.lua` now that's imported here

2023-12-14 02:52 UTC, Endaris commented on server/PADatabase.lua
> +  for row in selectPlayerRecordCount:rows() do
From what I can tell there is no good syntax to check whether a result set is empty or not, the best I found is 
```Lua
if selectPlayerRecordCount:columns() > 0 then
  return selectPlayerRecordCount:get_value(0)[1]
end
```
which honestly reads like crap. The iterator looks a bit jank but at least there are no doubts what is happening here while avoiding the attempt of accessing the first result of an empty result set.
Additionally this particular statement is only run on boot so speed is no concern compared to readability and safety imo.

2023-12-14 03:18 UTC, Endaris commented on server/Connection.lua
> +  if self.room == nil then
On one hand this could log griefing done by logging in and just flooding the server with input messages.
On the other hand, if you want to flood messages, you can also just get a room against yourself and flood menu_state updates, probably dozens of times more effective in terms of load and it logs nothing as far as I can tell. The only way this could grief harder is by flooding the log files with warn messages and filling up disk space.
I'm generally supportive of addressing ways for users to grief the service but it seems to be very much not in scope for this PR when general preventive measures in the suggested direction are still absent.

2023-12-14 03:18 UTC, Endaris commented on server/Connection.lua
> +    return
See below.

2023-12-14 03:44 UTC, Endaris commented
Overall seems good, aside from resolving merge conflicts, we just need to fix that bug with disconnecting other people and keep processing `choose_another_name` client side so we can treat the PR like any other in regards to the stable/beta update cycle.

2023-12-17 01:52 UTC, Endaris commented
Okay, so unsurprisingly I'll make everything changed client-side in this PR obsolete with #1040 eventually.

While working on that PR I stumbled over some known and unknown inconsistencies with the network protocol that I documented here:
- #1042 

Most of those are probably rather trivial but it would help *a lot* if these already made it to the live server so I don't have to do jank workarounds to be server compatible when going into cross-version testing with a bigger user base.
While I do plan to overhaul network to, it's definitely out of scope for now and I think we'll all have a lot more confidence in the new client if we can easily cross-test in multiplayer with the old.

If you could get back to this, that would be great!

2023-12-27 14:26 UTC, Endaris reviewed
I'll still need to do some testing but looks good overall.

2023-12-27 14:26 UTC, Endaris commented on server/server_file_io.lua
> +  local filename = "./leaderboard.csv"
I'd expect a filename, not a relative path with the naming.
And it probably works with just `leaderboard.csv` too?

2023-12-27 14:34 UTC, Endaris commented
> Though I wasn't seeing the player name inconsistency and the code looks right.

It's not really an inconsistency but more a meh behaviour.
In `Server:create_room` we explicitly get our opponent's name in the `opponent` field.
Name is sent *nowhere* else except as part of an on-going replay.
If a spectator joins, they don't get to know the names of who they are spectating they have to back-reference the lobby data for the room they requested. If someone is ever fast enough to request spectate on two rooms, it will be impossible to find out which room you're joining because the server doesn't tell the room number either.
Ideally, names would be attached to the message sent in `Room:add_spectator`. We could go `a_name`, `b_name` or follow a different convention based on player numbers. That way, clients don't have to try and backreference lobby data to find out who they're spectating.

2023-12-27 15:11 UTC, Endaris commented on serverLauncher.lua
> +require("server.tests.Tests")
Given that we may want to test client-server interactions in the future, I'm not sure if it's the best thing if server tests are isolated in their own folder.
Things like the mockup server object would definitely be useful for that. Can certainly worry about that later though, just a thought.

2023-12-27 15:11 UTC, Endaris approved these changes

2024-01-05 11:05 UTC, Endaris commented on server/Connection.lua
> +      assert(self.server.playerbase:nameTaken("", name) == false)
Even then I would think this is covered by `testLoginInvalidUserID()`
None of the other potential cases of not calling `canLogin` is being asserted against, so it stands out to me.
It should also at least have an error message attached so it's easier to identify what's wrong when checking logs.

2024-01-11 23:36 UTC, merged