Improve chain card in themes
panel-attack/panel-attack pull request #957
Opened 2023-08-20 04:20 UTC by JamesVanBoxtel

It was impossible to have old style 14x chain being the mystery chain.

Instead, assume the theme is going to provide its own chains if it provides any.

Also added chain images up to 99

2023-08-20 09:21 UTC, Endaris commented
> It was impossible to have old style 14x chain being the mystery chain.

Somehow my poor brain can't process what this is supposed to mean. It sounds like there was some kind of problem but I don't get what it is.

2023-08-21 02:46 UTC, Shosoul requested changes
I would like to propose this as an alternative:
 ```lua
  -- Chain card loading
  -- load as many chain cards as there are available
  -- we assume if the theme provided any chains, they want to control all of them so don't load backups
  local chainCards = FileUtil.getFilteredDirectoryItems(Theme.themeDirectoryPath .. self.name .. "/chain")
  local wantsBackupChainCards = #chainCards == 0
  if wantsBackupChainCards then -- No chains found, use defaults
    chainCards = FileUtil.getFilteredDirectoryItems(Theme.defaultThemeDirectoryPath .. "/chain")
  end
  for _, chainCard in pairs(chainCards) do 
    local number = string.match(chainCard, "%d+")
    self.images.IMG_cards[true][number] = self:load_theme_img("chain/chain" .. number, wantsBackupChainCards)
    self.chainCardLimit = math.max(self.chainCardLimit or number, number)
  end
  -- mystery chain
  local mysteryChainCard = self:load_theme_img("chain/chain00")
  -- This makes the table default to returning a mystery chain card if the number is not found
  setmetatable(self.images.IMG_cards[true], {__index = function () return mysteryChainCard end})
```
This allows us to load as many chains that exist in the file, and gaps in the chains will automatically be replaced with the `x?` graphic. Also, are we sure we want to have all of those graphics separately made instead of having the game generate them itself? It would be fewer files and save on storage.

2023-08-21 07:36 UTC, Endaris requested changes
> The default theme had chains up to 19. So if you wanted the classic way that only went to 13 you couldn't.

I tested this on current beta and as far as I can tell, this is...not the case?
The distinction we have right now for using the `useBackup` flag between chain numbers between 2 and 13 (using backup) and for 14 and above (*not* using backup) would assure that any theme would default to chain0 aka mystery chain for chains above 13.
I tested this by moving x14 chain cards and above from my Light theme into a different subfolder and x14 gives me x? as desired, without this PR.
The only benefit I see from this is that you can cut off for using mystery chain even BEFORE x13 which is...very niche as a use-case.

2023-08-21 07:36 UTC, Endaris commented on Theme.lua
> +    self.images.IMG_cards[false][i] = self:load_theme_img("combo/combo" .. tostring(math.floor(i / 10)) .. tostring(i % 10) .. "", true)
This change kind of goes against your intended purpose of giving theme creators more control. If there are any combo cards at all, it would only be consistent if the game only uses default cards instead of the mystery combo card if there aren't any combo cards in the theme at all.

2023-08-28 07:03 UTC, Endaris commented
> This allows us to load as many chains that exist in the file, and gaps in the chains will automatically be replaced with the `x?` graphic. Also, are we sure we want to have all of those graphics separately made instead of having the game generate them itself? It would be fewer files and save on storage.


I would rather leave that in good faith to theme creators. There isn't a good solution here that doesn't require the theme creators intervention as transitions between x? and actual numbers will be just as weird as a switch of art style in the middle. Jam's approach comparatively tells modders more clearly what we want from them than yours by being visually a bit more obnoxious so I would prefer that one. It's also slightly more readable because it uses the existing wrapper functions for dealing mod/fallback image loading.

More of a valuable discussion for combos due to discrete attack values on certain numbers rather than every single increment but not what this PR is doing.

2023-08-28 07:03 UTC, Endaris reviewed
Imo it would be good if we had this kind of change for combos as well for consistency but it does not need to be in this PR.

Having a combo00 is valuable for not forcing modders to make combo cards above 27 if they don't see a value when there is no extra garbage. 
I think that can still be discussed but I wouldn't have this PR remove the file if it only deals with chains as it is still the fallback via `Theme:comboImage` and just partially removing something while leaving loose ends seems wrong to me.

So after undoing the removal of combo00, consider this approved from my side

2023-09-25 17:33 UTC, Shosoul commented
I still think the other solution is cleaner but it's not something that has to be done at this moment, so I won't push it further. I do agree combo00 should stay, as well.

2023-09-26 13:10 UTC, Endaris approved these changes
We'll readd combo0 at a later point in time, I'll create a issue for that.

2023-09-26 13:16 UTC, merged