Reduce globals for asset loading
panel-attack/panel-attack pull request #976
Opened 2023-10-01 18:46 UTC by Endaris

I'm currently working on reimplementing selectScreen in all of its forms on Sankyr's UI rework.
I'll do parallel PRs to both beta and scenes for non-UI changes so we'll have less troubles porting changes later on.

This change in particular is a preparation to move away from the global `refreshBasedOnOwnMods` which is rather verbose and a bit complicated and mixes rather different use-cases (online vs local) and I want to get rid of it in the select screen of the new UI. I already replaced it in places where it didn't bloat code too much.
Additionally we had different functions doing similar things like the former `wait_for_random_character` which has been removed in favor of an explicit implementation using the new functions.
The implementation in this PR in particular makes sure that there cannot be a crash when bundles are nested further than 1 level and bundles.
Additionally the globals in character_loader had already been declared in globals.lua so this takes care of it.

Future PRs of this type will go against sceneRefactor instead but I'll first need to merge beta against that which will take a while because I still need to get into Sankyr's codebase to resolve some of the conflicts.

2023-10-06 13:37 UTC, Sankyr approved these changes

2023-10-08 19:01 UTC, Shosoul commented
Will check this out more in detail tonight if I get time

2023-10-11 05:01 UTC, Shosoul requested changes
When attempting to spectate a game:
```
Error

Stack Trace:     stage_loader.lua: in function 'resolveStageSelection'
    select_screen/select_screen.lua:809: in function 'handleServerMessages'
    select_screen/select_screen.lua:1021: in function 'func'
Username: Shosoul_Dev
Theme: Panel Attack Modern
Error Message: main.lua:148: stage_loader.lua:74: attempt to index upvalue 'tableUtils' (a boolean value)
Engine Version: 047
Build Version: Unknown
Operating System: OS: Windows
Love Version: 11.4.0
UTC Time: 2023-10-11 05:00:06```

2023-10-14 14:30 UTC, Endaris commented
Yeah, mb, I only tested this against myself but that never took that code path.
Guilty of pasting code over, should be fine now.

2023-10-31 23:31 UTC, merged